<link rel="stylesheet" href="<?php echo $this->baseUrl; ?>/validador/fancyBox/jquery.fancybox-1.3.4.css" type="text/css"/> 


<div id="divNuevoArticulo"  class="fancyNormal" style="overflow: hidden"> 
    <form id="frmCrear" class="tbBorde">
        <table class="centrar alinearIzquierda" >


            <tr>
                <td colspan="6" align="center">
                    <H4 class="panel panel-primary btn-primary">INFORMACIÓN GENERAL</H4>
                    <br>
                    <br>
                </td>
            </tr>
            <br>
            <tr>
                <td>
                    Primer Apellido
                </td>
                <td>
                    <input type="text" class="form-control" id="txtPrimerApellido" 
                           data-validation-engine="validate[required,onlyLetterSp]"
                           placeholder="Primer apellido">
                </td>

                <td>
                    Segundo Apellido
                </td>
                <td>
                    <input type="text" class="form-control" id="txtSegundoApellido"
                           data-validation-engine="validate[required,onlyLetterSp]"
                           placeholder="Segundo apellido">
                </td>

            </tr>
            <tr>
                <td>
                    Nombres
                </td>
                <td colspan="2">
                    <input type="text" class="form-control" id="txtNombre"
                           data-validation-engine="validate[required,onlyLetterSp]"
                           placeholder="Ingrese Nombres">
                </td>
            </tr>
            <tr>

                <td>
                    Documento Identidad
                </td>
                <td>
                    <input type="text" class="form-control" id="txtNombre"
                           data-validation-engine="validate[required]"
                           placeholder="Documento">
                </td>

                <td>
                    Fecha de Nacimiento
                </td>
                <td>
                    <input type="text" class="span2 form-control" id="txtFechaNacimiento"
                           data-validation-engine="validate[required,custom[date]]"
                           placeholder="Dia/Mes/Año">
                </td>
            </tr>
            <tr>
                <td colspan="4">
                    <hr>
                </td>
            </tr>
            <tr>
                <td>
                    Código
                </td>
                <td>
                    <input type="text" class="form-control" id="txtCodigo"
                           data-validation-engine="validate[required,custom[onlyNumberSp,minSize[11]]]"
                           placeholder="CodigoUD"> 

                </td>
                <td>
                    Semestre
                </td>
                <td>
                    <input type="text" class="form-control" id="txtSemestre"
                           data-validation-engine="validate[required,custom[integer],min[0]]"
                           placeholder="Actual"> 

                </td>

            </tr>
            <tr>
                <td>
                    Facultad
                </td>
                <td>
                    <select class="form-control checkbox-inline" 
                            id="selFacultad" 
                            data-validation-engine="validate[required]"
                            data-errormessage="Elija una opcion">
                        <option value="">-- SELECCIONE --</option>
                        <option value="1">Tecnológica</option></select>
                </td>
                <td>
                    Proyecto Curricular
                </td>
                <td>
                    <select class="form-control checkbox-inline"
                            id="selProyectoCurricular"
                            data-validation-engine="validate[required]"
                            data-errormessage="Elija una opcion">
                        <option value="">-- SELECCIONE --</option>
                        <option value="1">Electrónica</option>
                    </select>
                </td>

            </tr>


            <tr>
                <td colspan="4">
                    <hr>
                </td>
            </tr>
            <tr>
                <td>
                    Dirección
                </td>
                <td>
                    <input type="text" class="form-control" id="txtDireccion"
                           data-validation-engine="validate[required]"
                           placeholder="Dirección">
                </td>
                <td>
                    Teléfono
                </td>
                <td>
                    <input type="text" class="form-control" id="txtTelefono"
                           placeholder="Número de telefono" 
                           data-validation-engine="validate[required,custom[onlyNumberSp,minSize[7]]]">
                </td>

            </tr>
            <tr>
                <td>
                    Estrato
                </td>
                <td>
                    <select class="form-control checkbox-inline" 
                            id="selEstrato" 
                            data-validation-engine="validate[required]"
                            data-errormessage="Elija una opcion">
                        <option value="">-- SELECCIONE --</option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                    </select>

                </td>
                <td>
                    Afiliación EPS
                </td>
                <td>
                    <input type="text" class="form-control" id="txtAfiliacion"
                           data-validation-engine="validate[required,onlyLetterSp]"
                           placeholder="Tipo Eps"> 

                </td>

            </tr>
            <tr>
                <td>
                    Emergencia Llamar a
                </td>
                <td>
                    <input type="text" class="form-control" id="txtEmergencia"
                           placeholder="Numero"
                           data-validation-engine="validate[required,custom[onlyNumberSp,minSize[7]]]"> 
                </td>
                <td>
                    Telénofos (s)
                </td>
                <td>
                    <input type="text" class="form-control" id="txtTelEmergencia"
                           placeholder="Numero"
                           data-validation-engine="validate[required,custom[onlyNumberSp,minSize[7]]]"> 

                </td>
            <br>
            </tr>
            <tr>
                <td>
                    <br>    
                </td>
            </tr>
            <tr>
                <td>Descripción</td>
                <td colspan="3">
                    <textarea class="descripcion form-control" placeholder="Información adicional u observaciones"></textarea>
                </td>
            </tr>
            <tr>
                <td>
                    <br>
                </td>
            </tr>
            <tr>
                <td colspan="6">
                    <hr>
                </td>
            </tr>
            <tr>
                <td colspan="6" align="center">
                    <table class="centrar">
                        <tbody><tr>

                                <td align="center" colspan="6">
                                    <input type="button" class="btn-primary btn-large" value="Guardar"> 
                                </td>

                            </tr>
                        <br>
                        </tbody>
                    </table>
                </td>
            </tr>
            <tr>
                <td>
                    <br>    
                </td>
            </tr>
        </table>
    </form>
</div>