<div id="divNuevoArticulo"  class="fancyNormal" style="overflow: hidden"> 
    <form class="tbBorde" style="text-align: left">
    <table class="centrar alinearIzquierda" >


        <tr>
            <td colspan="6" align="center">
                <H4 class="panel panel-primary btn-primary">TRATAMIENTO EJECUTADO</H4>
                <br>
                <br>
            </td>
        </tr>
        <br>
        <tr>
            <td>
                Plan de Tratamiento
            </td>
            <td>
                <select class="form-control" id="selPlanTratamiento" >
                <option value="-1">-- SELECCIONE --</option>
                <option value="1">Opeartoria</option>
                <option value="1">Periodoncia</option>
                <option value="1">Ortodoncia</option>
                <option value="1">Medicina Oral</option>
                <option value="1">Cirugía Horal</option>
                <option value="1">Endodoncia</option>
                <option value="1">Prótesis</option>
            </td>
        </tr>
        <tr>
                <td colspan="6">
                    <hr>
                </td>
            </tr>
        <tr>
            <td>
                Fecha
            </td>
            <td>
                <input type="text" class="form-control" id="txtFecha">
            </td>
            <td>
                Hora
            </td>
            <td>
                <input type="text" class="form-controlPequenio" id="txtHora"> 
            </td>
        </tr>
        <tr>
            <td>
        Diente        
            </td>
            <td>
             <input type="text" class="form-controlPequenio" id="txtDiente">    
            </td>
            <td>
        Superficie        
            </td>
            <td>
             <input type="text" class="form-controlPequenio" id="txtDiente">    
            </td>
        </tr>
        <tr><td><br></td></tr><tr>
        <tr><td><b>Actividad</b></td></tr>
        <tr>
            
            <td colspan="3">
                
                <textarea class="descripcion form-control"id=txtAreaActividad""></textarea>
                
            </td></tr>
         <tr>
                <td colspan="6">
                    <hr>
                </td>
            </tr>
        
            <tr>
                <td>
                    Firma Paciente
                </td>
                
            </tr>
            <tr><td>
                    <textarea  id="txtAreaActividad" class="form-controlPequenio"></textarea>
                </td></tr>
            <tr>
                <td>
                    Firma Paciente
                </td>
                
            </tr>
            <tr><td>
                    <textarea  id="txtAreaActividad" class="form-controlPequenio"></textarea>
                </td></tr>
             <tr>
                <td colspan="6">
                    <hr>
                </td>
            </tr>
        <tr>
            
        <tr>
            <td colspan="6" align="center">
                <table class="centrar">
                    <tbody><tr>

                            <td align="center" colspan="6">
                                <input type="button" class="btn-primary btn-large" value="Guardar"> 
                            </td>

                        </tr>
                    <br>
                    </tbody>
                </table>
            </td>
        </tr>
        <tr>
            <td>
                <br>    
            </td>
        </tr>
        </table>
    </form>
</div>