<div id="divNuevoArticulo"  class="fancyNormal" style="overflow: hidden"> 
    <form class="tbBorde" style="text-align: left">
        <table class="centrar alinearIzquierda">
            <tr>
                <td colspan="6" align="center">
                    <H4 class="panel panel-primary btn-primary">HISTORIA CLÍNICA URGENCIAS</H4>
                    <br>
                    <br>
                </td>
            </tr>
            <br>
            <tr>
                <td>
                    Tratamiento Médico
                </td>
                <td>
                    <select class="selectPequenio span1" id="selTratamientoMedico" >
                        <option value="-1">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                        <option value="3">No Sabe</option>
                    </select>
                </td>
                <td>
                    Ingestión de Medicamentos
                </td>
                <td>
                    <select class="selectPequenio span1" id="selIngestionMedicamentos" >
                        <option value="-1">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                        <option value="3">No Sabe</option>
                    </select>
                </td>

            </tr>
            <tr>
                <td>
                    Hemorragias
                </td>
                <td>
                    <select class="selectPequenio span1" id="selHemorragias" >
                        <option value="-1">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                        <option value="3">No Sabe</option>
                    </select>
                </td>
                <td>
                    Hipertension Arterias
                </td>
                <td>
                    <select class="selectPequenio span1" id="selHipArterial" >
                        <option value="-1">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                        <option value="3">No Sabe</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                    Cardiopatias
                </td>
                <td>
                    <select class="selectPequenio span1" id="selCardiopatias" >
                        <option value="-1">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                        <option value="3">No Sabe</option>
                    </select>
                </td>
                <td>
                    Diabetes
                </td>
                <td>
                    <select class="selectPequenio span1" id="selDiabetes" >
                        <option value="-1">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                        <option value="3">No Sabe</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                    Fiebre Reumática
                </td>
                <td>
                    <select class="selectPequenio span1" id="selFiebreReu" >
                        <option value="-1">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                        <option value="3">No Sabe</option>
                    </select>
                </td>
                <td>
                    Hepatitis
                </td>
                <td>
                    <select class="selectPequenio span1" id="selHepatitis" >
                        <option value="-1">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                        <option value="3">No Sabe</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                    Reacciones Alérgicas
                </td>
                <td>
                    <select class="selectPequenio span1" id="selReaccionesAlergicas" >
                        <option value="-1">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                        <option value="3">No Sabe</option>
                    </select>
                </td>
            </tr>
              <tr>
                <td colspan="6">
                    <hr>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    Otras Enfermedades
                </td>
                <td>
                    <select class="selectPequenio span1" id="selOtrasEnfermedades" >
                        <option value="-1">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                        <option value="3">No Sabe</option>
                    </select>
                </td>
            </tr>
            <td>
                Cúales?
            </td>
            <tr>

                <td colspan="4">
                    <textarea class="descripcion form-control" id="txtObservaciones"></textarea>
                </td>
            </tr>
            <tr>
                <td>
                    Hallazgos clínicos
                </td>
            </tr>
            <tr>

                <td colspan="3">
                    <textarea class="descripcion form-control" id="txtAllazgos"></textarea>
                </td>
            </tr>
            <tr>
                <td>
                    Motivo de la Consulta
                </td>
            </tr>
            <tr>

                <td colspan="3">
                    <textarea class="descripcion form-control" id="txtMotivo"></textarea>
                </td>
            </tr>
            
            <tr>
                <td colspan="6">
                    <hr>
                </td>
            </tr>


            <tr>
                <td colspan="6" align="center">
                    <table class="centrar">
                        <tbody><tr>

                                <td align="center" colspan="6">
                                    <input type="button" class="btn-primary btn-large" value="Guardar"> 
                                </td>

                            </tr>
                        <br>
                        </tbody>
                    </table>
                </td>
            </tr>
            <tr>
                <td>
                    <br>    
                </td>
            </tr>
        </table>
    </form>
</div>