<link rel="stylesheet" href="<?php echo $this->baseUrl; ?>/validador/fancyBox/jquery.fancybox-1.3.4.css" type="text/css"/> 

<div id="divNuevoArticulo"  class="fancyNormal" style="overflow: hidden"> 
    <form class="tbBorde" style="text-align: left">
        <table class="centrar alinearIzquierda" >
            <tr>
                <td colspan="6" align="center">
                    <H4 class="panel panel-primary btn-primary">ANÉMESIS</H4>
                    <br>
                    <br>
                </td>
            </tr>
            <br>
            <tr>
                <td>
                    Tratamiento Médico
                </td>
                <td>
                    <select class="selectPequenio span1" id="selTratamientoMedico" >
                        <option value="-1">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                        <option value="3">No Sabe</option>
                    </select>
                </td>
                <td>
                    Ingestión de Medicamentos
                </td>
                <td>
                    <select class="selectPequenio span1" id="selIngestionMedicamentos" >
                        <option value="-1">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                        <option value="3">No Sabe</option>
                    </select>
                </td>
                <td>
                    Reacciones Alérgicas
                </td>
                <td>
                    <select class="selectPequenio span1" id="selReaccionesAlergicas" >
                        <option value="-1">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                        <option value="3">No Sabe</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                    Hemorragias
                </td>
                <td>
                    <select class="selectPequenio span1" id="selHemorragias" >
                        <option value="-1">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                        <option value="3">No Sabe</option>
                    </select>
                </td>
                <td>
                    Irradiaciones
                </td>
                <td>
                    <select class="selectPequenio span1" id="selIrradiaciones" >
                        <option value="-1">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                        <option value="3">No Sabe</option>
                    </select>
                </td>
                <td>
                    Sinusitis
                </td>
                <td>
                    <select class="selectPequenio span1" id="selSinusitis" >
                        <option value="-1">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                        <option value="3">No Sabe</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                    Enfermedades Respiratorias
                </td>
                <td>
                    <select class="selectPequenio span1" id="selEnfRespiratorias" >
                        <option value="-1">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                        <option value="3">No Sabe</option>
                    </select>
                </td>
                <td>
                    Cardiopatias
                </td>
                <td>
                    <select class="selectPequenio span1" id="selCardiopatias" >
                        <option value="-1">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                        <option value="3">No Sabe</option>
                    </select>
                </td>
                <td>
                    Diabetes
                </td>
                <td>
                    <select class="selectPequenio span1" id="selDiabetes" >
                        <option value="-1">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                        <option value="3">No Sabe</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                    Fiebre Reumática
                </td>
                <td>
                    <select class="selectPequenio span1" id="selFiebreReu" >
                        <option value="-1">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                        <option value="3">No Sabe</option>
                    </select>
                </td>
                <td>
                    Hepatitis
                </td>
                <td>
                    <select class="selectPequenio span1" id="selHepatitis" >
                        <option value="-1">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                        <option value="3">No Sabe</option>
                    </select>
                </td>
                <td>
                    Hipertension Arterias
                </td>
                <td>
                    <select class="selectPequenio span1" id="selHipArterial" >
                        <option value="-1">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                        <option value="3">No Sabe</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                    Otras Enfermedades
                </td>
                <td>
                    <select class="selectPequenio span1" id="selOtrasEnfermedades" >
                        <option value="-1">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                        <option value="3">No Sabe</option>
                    </select>
                </td>
                <td>
                    Antecedentes Familiares
                </td>
                <td>
                    <select class="selectPequenio span1" id="selAntFamiliares" >
                        <option value="-1">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                        <option value="3">No Sabe</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td colspan="6">
                    <hr>
                </td>
            </tr>
            <tr>
                <td>
                    Otros
                </td>
            </tr>
            <tr>
                <td colspan="3">
                    <textarea class="descripcion form-control"></textarea>
                </td>
            </tr>
            <tr>
                <td colspan="6">
                    <hr>
                </td>
            </tr>
            <tr>
                <td>
                    <b>Hábitos de Igiene Oral</b>
                </td>
            </tr>
            <tr><td>
                    <br>
                </td></tr>
            <tr>
                <td>
                Cepillado    
                </td>
                <td>
                    <select class="selectPequenio span1" id="SelCepillado" >
                        <option value="-1">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                Seda Dental    
                </td>
                 <td>
                    <select class="selectPequenio span1" id="selSedaDental" >
                        <option value="-1">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                Enjuague    
                </td>
                 <td>
                    <select class="selectPequenio span1" id="selEnjuague">
                        <option value="-1">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                    </select>
                </td>
            </tr>
            
            <tr>
                <td><br></td>
            </tr>
            <tr>
                <td>
                    Observaciones
                </td>
            </tr>
            <tr>
                
                <td colspan="3">
                    <textarea class="descripcion form-control" id="txtObservaciones"></textarea>
                </td>
            </tr>
            <tr>
                <td colspan="6">
                    <hr>
                </td>
            </tr>
            <tr>
                <td>
                    <b>Signos Vitales</b>
                </td>
            </tr>
            <tr>
                <td>
                    <br>
                </td>
            </tr>
            <tr>
            <tr>
                <td>
                    Temperatura
                </td>
                <td>
                     <input type="text" class="form-controlPequenio" id="txtTemperatura"> 
                </td>
           
                <td>
                    Pulso
                </td>
                <td>
                     <input type="text" class="form-controlPequenio" id="txtPulso"> 
                </td>
            </tr>
            <tr>
                <td>
                    Tension Arterial
                </td>
                <td>
                     <input type="text" class="form-controlPequenio" id="txtTenArterial"> 
                </td>
            
                <td>
                    Respiracion
                </td>
                <td>
                     <input type="text" class="form-controlPequenio" id="txtRespiracion"> 
                </td>
            </tr>
            <tr>
                <td colspan="6">
                    <hr>
                </td>
            </tr>
            
            
            <tr>
                <td colspan="6" align="center">
                    <table class="centrar">
                        <tbody><tr>

                                <td align="center" colspan="6">
                                    <input type="button" class="btn-primary btn-large" value="Guardar"> 
                                </td>

                            </tr>
                        <br>
                        </tbody>
                    </table>
                </td>
            </tr>
            <tr>
                <td>
                    <br>    
                </td>
            </tr>
        </table>
    </form>
</div>