<script>
    $(document).ready(function() {
        //Inicializamos la libreria validadora para el formulario con id (nombre), "frmCrear"
        $("#frmUrgAnamnesis").validationEngine();
    });

    $('#btnGuardar').click(function() {

        //Si el formulario esta validado, entonces...
        if ($('#frmUrgAnamnesis').validationEngine('validate')) {
           alert("Datos almacenado satisfactoriamente");
        }

    });
</script>
<div id="divNuevoArticulo"  class="fancyNormal" style="overflow: hidden"> 
    <form id="frmUrgAnamnesis" class="tbBorde" style="text-align: left">
        <table class="centrar alinearIzquierda">
            <tr>
                <td colspan="6" align="center">
                    <H4 class="panel panel-primary btn-primary">HISTORIA CLÍNICA URGENCIAS</H4>
                    <br>
                    <br>
                </td>
            </tr>
            <br>
            <tr>
                <td>
                    Tratamiento Médico
                </td>
                <td>
                    <select class="selectPequenio span1" 
                            id="selTratamientoMedico" 
                            data-validation-engine="validate[required]"
                            data-errormessage="Seleccione una opción">
                        <option value="">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                        <option value="3">No Sabe</option>
                    </select>
                </td>
                <td>
                    Ingestión de Medicamentos
                </td>
                <td>
                    <select class="selectPequenio span1" 
                            id="selIngestionMedicamentos" 
                            data-validation-engine="validate[required]"
                            data-errormessage="Seleccione una opción">
                        <option value="">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                        <option value="3">No Sabe</option>
                    </select>
                </td>

            </tr>
            <tr>
                <td>
                    Hemorragias
                </td>
                <td>
                    <select class="selectPequenio span1" 
                            id="selHemorragias" 
                            data-validation-engine="validate[required]"
                            data-errormessage="Seleccione una opción">
                        <option value="">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                        <option value="3">No Sabe</option>
                    </select>
                </td>
                <td>
                    Hipertension Arterias
                </td>
                <td>
                    <select class="selectPequenio span1" 
                            id="selHipArterial"
                            data-validation-engine="validate[required]"
                            data-errormessage="Seleccione una opción">
                        <option value="">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                        <option value="3">No Sabe</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                    Cardiopatias
                </td>
                <td>
                    <select class="selectPequenio span1" 
                            id="selCardiopatias"
                            data-validation-engine="validate[required]"
                            data-errormessage="Seleccione una opción">
                        <option value="">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                        <option value="3">No Sabe</option>
                    </select>
                </td>
                <td>
                    Diabetes
                </td>
                <td>
                    <select class="selectPequenio span1" 
                            id="selDiabetes" 
                            data-validation-engine="validate[required]"
                            data-errormessage="Seleccione una opción">
                        <option value="">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                        <option value="3">No Sabe</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                    Fiebre Reumática
                </td>
                <td>
                    <select class="selectPequenio span1" 
                            id="selFiebreReu" 
                            data-validation-engine="validate[required]"
                            data-errormessage="Seleccione una opción">
                        <option value="">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                        <option value="3">No Sabe</option>
                    </select>
                </td>
                <td>
                    Hepatitis
                </td>
                <td>
                    <select class="selectPequenio span1" 
                            id="selHepatitis" 
                            data-validation-engine="validate[required]"
                            data-errormessage="Seleccione una opción">
                        <option value="">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                        <option value="3">No Sabe</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                    Reacciones Alérgicas
                </td>
                <td>
                    <select class="selectPequenio span1" 
                            id="selReaccionesAlergicas" 
                            data-validation-engine="validate[required]"
                            data-errormessage="Seleccione una opción">
                        <option value="">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                        <option value="3">No Sabe</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td colspan="6">
                    <hr>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    Otras Enfermedades
                </td>
                <td>
                    <select class="selectPequenio span1" 
                            id="selOtrasEnfermedades" 
                            data-validation-engine="validate[required]"
                            data-errormessage="Seleccione una opción">
                        <option value="">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                        <option value="3">No Sabe</option>
                    </select>
                </td>
            </tr>
            <td>
                Cúales?
            </td>
            <tr>

                <td colspan="4">
                    <textarea class="descripcion form-control" 
                              id="txtObservaciones">
                    </textarea>
                </td>
            </tr>
            <tr>
                <td>
                    Hallazgos clínicos
                </td>
            </tr>
            <tr>

                <td colspan="3">
                    <textarea class="descripcion form-control" 
                              id="txtAllazgos">
                    </textarea>
                </td>
            </tr>
            <tr>
                <td>
                    Motivo de la Consulta
                </td>
            </tr>
            <tr>

                <td colspan="3">
                    <textarea class="descripcion form-control" 
                              id="txtMotivo"
                              data-validation-engine="validate[required]">
                    </textarea>
                </td>
            </tr>

            <tr>
                <td colspan="6">
                    <hr>
                </td>
            </tr>


            <tr>
                <td colspan="6" align="center">
                    <table class="centrar">
                        <tbody><tr>

                                <td align="center" colspan="6">
                                    <input type="submit" class="btn-primary btn-large" 
                                           id="btnGuardar" value="Guardar"> 
                                </td>

                            </tr>
                        <br>
                        </tbody>
                    </table>
                </td>
            </tr>
            <tr>
                <td>
                    <br>    
                </td>
            </tr>
        </table>
    </form>
</div>