<div id="divNuevoArticulo"  class="fancyNormal" style="overflow: hidden"> 
    <form class="tbBorde" id="hisotoriaUrgencia" style="text-align: left">
    <table class="centrar">


        <tr>
            <td colspan="6" align="center">
                <H4 class="panel panel-primary btn-primary">DATOS BASICOS</H4>
                <br>
                <br>
            </td>
        </tr>
        <br>
        <tr>
            <td>
                Nombres y Apellidos
            </td>
            <td colspan="5">
                <input type="text" class="form-control" id="txtNombreApellido">
            </td>

        </tr>
        <tr>
             <td>
                Código
            </td>
            <td colspan="1">
                <input type="text" class="form-control" id="txtCodigo">
            </td>
             <td>
                Fecha de Nacimiento
            </td>
            <td>
                <input type="text" class="form-control" id="txtFechaNacimiento">
            </td>
        </tr>
        <tr>
            <td>
                Edad
            </td>
            <td>
                <input type="text" class="form-control" id="txtEdad">
            </td>
            <td>
                Documento Identidad
            </td>
            <td>
                <input type="text" class="form-control" id="txtDocIdentidad">
            </td>
        </tr>
        <tr>
            <td colspan="4">
                 <hr>
            </td>
        </tr>
        <tr>
            <td>
                Tipo Vinculacion
            </td>
            <td>
               <select class="form-control" id="selTivinculacion">
                    <option value="-1">-- SELECCIONE --</option>
                    <option value="1">Estudiante</option>
                    <option value="1">Funcionario</option>
                    <option value="1">Vinculación Especial</option>
               </select> 
            </td>
            <td>
                Proyecto Curricular
            </td>
            <td>
                <select class="form-control" id="selProyCurricular">
                    <option value="-1">-- SELECCIONE --</option>
                    <option value="1">T. Sistemas</option>
                    <option value="1">T. Electrónica</option>
                    <option value="1">T. Mecánica</option>
                    <option value="1">T. Inustrial</option>
                    <option value="1">T. Eléctrica</option>
                </select> 
            </td>
           
        </tr>
        <tr>
             <td>
                Dependencia
            </td>
            <td>
                <input type="text" class="form-control" id="txtDependencia">
            </td>
        </tr>
        <tr>
            <td>
                EPS
            </td>
            <td>
                <input type="text" class="form-controlPequenio" id="txtEps"> 
            </td>
            <td>
                sexo
            </td>
            <td>
               <input type="text" class="form-controlPequenio" id="txtDependencia"> 
            </td>
            </tr>
            <tr>
                 <td>
                Estado civil
            </td>
                <td>
              <select class="form-control form-control" id="selEstadoCivil">
                    <option value="-1">-- SELECCIONE --</option>
                    <option value="1">Casado(a)</option>
                    <option value="1">Soltero(a)</option>
                    <option value="1">Union Libre</option>
                </select>   
            </td>
            </tr>
        <tr>
            <td colspan="4">
                 <hr>
            </td>
        </tr>
        <tr>
            <td>
                Procedente de
            </td>
            <td colspan="4">
                <input type="text" class="form-control" id="txtProcedente">
            </td>
        </tr>
        <tr>
             <td>
                Dirección Actual de Residencia
            </td>
            <td>
                <input type="text" class="form-control" id="txtDireccionActual">
            </td>
            <td>
                Teléfono
            </td>
            <td>
                <input type="text" class="form-control" id="txtTelefono">
            </td>
            
        </tr>
         <tr>
            <td colspan="6">
                <hr>
            </td>
        </tr>
        <tr>
            <td style="width: 140px"> 
                En emergencia Llamar a:
            </td>
            <td colspan="3"> 
               <input type="text" class="form-control" id="txtEmergencia"> 
            </td>           
        </tr>
        <tr>
            <td>Parentesco</td>
            <td> 
               <input type="text" class="form-control" id="txtParentesco"> 
            </td>
            <td>
             Dirección   
            </td>
            <td>
             <input type="text" class="form-control" id="txtDireccionAcompa">    
            </td>
        </tr>
        <tr>
            <td>
                Teléfonos
            </td>
            <td>
                <input type="text" class="form-control" id="txtTel1">    
            </td>
            <td>
                <input type="text" class="form-control" id="txttel2">    
            </td>
        </tr>
        <tr>
            <td colspan="6">
                <hr>
            </td>
        </tr>
        <tr>
            <td colspan="6" align="center">
                <table class="centrar">
                    <tbody><tr>

                            <td align="center" colspan="6">
                                <input type="button" class="btn-primary btn-large" value="Guardar"> 
                            </td>

                        </tr>
                    <br>
                    </tbody>
                </table>
            </td>
        </tr>
        <tr>
            <td>
                <br>    
            </td>
        </tr>
        </table>
    </form>
</div>