<!--?php echo $this->layout()->content; ?>-->
<html lang="es">    
    <head>
        <meta charset="utf-8"/>
        <title>Bienestar</title>
        <link rel="shortcut icon" href="<?php echo $this->baseUrl; ?>./imagenes/favicon.ico">
        <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
        <meta content="" name="description"/>
        <meta content="" name="author"/>

        <link rel="stylesheet" href="<?php echo $this->baseUrl; ?>./bootstrap-3/dist/css/bootstrap.css">

        <link rel="stylesheet" href="<?php echo $this->baseUrl; ?>./bootstrap-3/assets/css/bootstrap-responsive.css">

        <!-- Tema opcional -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl; ?>./bootstrap-3/dist/css/bootstrap-theme.css">

        <link rel="stylesheet" href="<?php echo $this->baseUrl; ?>./bootstrap-3/assets/css/docs.css">


        <!-- Versión compilada y comprimida del JavaScript de Bootstrap -->
        <script src="<?php echo $this->baseUrl; ?>./bootstrap-3/dist/js/bootstrap.min.js"></script>

    </head>

    <body>  
        <header>
            <!--?php include 'header.php';?>-->
            <img id="banner" src="./imagenes/banner.png"/>
        </header>

        <!--menus-->
        <nav>
            <div class="navbar navbar-default">
                <?php echo $this->render('nav.phtml'); ?> 
            </div>
            <div>
                <div class="container-fluid">
                    <div class="row-fluid">
                        <div class="span2">
                            <!--Sidebar content-->
                            <div id="sidebar">
                                <?php echo $this->render('sidebar.phtml'); ?> 
                            </div>
                        </div>

                        </nav>

                        <div class="span10">
                            <!--Body content-->       
                            <div class="page-content" style="text-align: center">
                                <div id="content">
                                    <!--?php echo $this->layout()->content; ?><!--Enviamos los contenidos de todas las vistas-->
                                    <div class="container">
                                        <section id="gridSystem">
                                            <div class="bs-docs-grid">
                                                <div class="row show-grid">
                                                    <table class="table">
                                                        <div class="span2" data-original-title title>hola</div>
                                                        <div class="span2" data-original-title title>mundo</div>
                                                        <div class="span2" data-original-title title>tets</div>
                                                    </table>
                                                </div>
                                            </div>
                                        </section>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

    </body>
    <footer>
        <div>
            <?php echo $this->render('footer.phtml'); ?>
        </div>
    </footer>
</html> 