<!--?php echo $this->layout()->content; ?>-->
<html lang="es">    
    <head>
        <meta charset="utf-8"/>
        <title>Bienestar</title>
        <link rel="shortcut icon" href="<?php echo $this->baseUrl; ?>./imagenes/favicon.ico">
        <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
        <meta content="" name="description"/>
        <meta content="" name="author"/>
        
<link rel="stylesheet" href="<?php echo $this->baseUrl; ?>./bootstrap-3/dist/css/bootstrap.min.css">
 
<!-- Tema opcional -->
<link rel="stylesheet" href="<?php echo $this->baseUrl; ?>./bootstrap-3/dist/css/bootstrap-theme.min.css">
 
<!-- Versión compilada y comprimida del JavaScript de Bootstrap -->
<script src="<?php echo $this->baseUrl; ?>./bootstrap-3/dist/js/bootstrap.min.js"></script>
    </head>
    <body>
        <div class="form-content-box">
        <?php echo $this->layout()->content; ?>
        </div>
    </body>
</html>