<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="es"> <!--<![endif]-->
    <HEAD>
        <meta charset="utf-8" />
        <title>Bienestar</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport" />
        <meta content="" name="description" />
        <meta content="" name="author" />
        
        <!-- Bootstrap core CSS -->
        <link href="<?php echo $this->baseUrl; ?>./bootstrap-3/dist/css/bootstrap.css" rel="stylesheet" type="text/css" />

        <!-- Bootstrap theme CSS-->
        <link href="<?php echo $this->baseUrl; ?>./bootstrap-3/dist/css/bootstrap-theme.css" rel="stylesheet" type="text/css"/>

        <!--validator theme CSS-->
        <link rel="stylesheet" href="<?php echo $this->baseUrl; ?>./validador/css/validationEngine.jquery.css" type="text/css"/>
        <link rel="stylesheet" href="<?php echo $this->baseUrl; ?>./validador/css/template.css" type="text/css"/>

        <!-- Custom styles for this template -->
        <link href="<?php echo $this->baseUrl; ?>./bootstrap-3/dist/css/sticky-footer-navbar.css" rel="stylesheet" type="text/css"/>

        <!--library-->
        <script src="<?php echo $this->baseUrl; ?>./bootstrap-3/assets/js/jquery.js"></script>
        <script src="<?php echo $this->baseUrl; ?>./bootstrap-3/dist/js/bootstrap.js" type="text/javascript" charset="utf-8"></script>
        <script src="<?php echo $this->baseUrl; ?>./validador/js/jquery-1.8.2.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl; ?>./validador/js/languages/jquery.validationEngine-es.js" type="text/javascript" charset="utf-8"></script>
        <script src="<?php echo $this->baseUrl; ?>./validador/js/jquery.validationEngine.js" type="text/javascript" charset="utf-8"></script> 
        
    </HEAD>

    <BODY>  
        <header>
          <?php include 'header.php';?>
          <!--<img id="banner" src="./imagenes/banner.png"/>-->
        </header>

        <!--menus-->
        <nav>
            <div class="navbar navbar-default">
                <?php echo $this->render('nav.phtml'); ?> 
            </div>
            <div id="sidebar">
                <?php echo $this->render('sidebar.phtml'); ?> 
            </div>
        </nav>

        <div class="page-content">
            <div id="content">
                 <div>
                      <?php echo $this->layout()->content; ?><!--Enviamos los contenidos de todas las vistas-->
                 </div>
            </div>
        </div>
    </BODY>
    <FOOTER class="panel-footer">
         <?php echo $this->render('footer.phtml'); ?>
    </FOOTER>
</HTML> 