<div id="divNuevoArticulo"  class="fancyNormal" style="overflow: hidden"> 
    <form class="tbBorde" style="text-align: left">
        <table class="centrar alinearIzquierda" >
            <tr>
                <td colspan="6" align="center">
                    <H4 class="panel panel-primary btn-primary">EXAMEN FÍSICO ESTOMATOLÓGICO</H4>
                    <br>
                    <br>
                </td>
            </tr>
            <br>
            <tr>
                <td colspan="2">
                    Examen Temporo-Mandibular
                </td>
                <td>
                    <select class="selectPequenio span1" id="selExTemMandibular" >
                        <option value="-1">----</option>
                        <option value="1">Normal</option>
                        <option value="2">Anormal</option>
                    </select>
                </td>
            </tr>
            <tr><td><br></td></tr>
            <tr>
                <td>
                    <b>MUCOSA BUCAL</b>
                </td>
            </tr>
            <tr><td><br></td></tr>
            <tr>
                <td colspan="2">
                    Labios
                </td>
                <td>
                    <select class="selectPequenio span1" id="selLabios" >
                        <option value="-1">----</option>
                        <option value="1">Normal</option>
                        <option value="2">Anormal</option>
                    </select>
                </td>
                <td colspan="2">
                    Lengua
                </td>
                <td>
                    <select class="selectPequenio span1" id="selLengua" >
                        <option value="-1">----</option>
                        <option value="1">Normal</option>
                        <option value="2">Anormal</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    Paladar
                </td>
                <td>
                    <select class="selectPequenio span1" id="selPaladar" >
                        <option value="-1">----</option>
                        <option value="1">Normal</option>
                        <option value="2">Anormal</option>
                    </select>
                </td>
                <td colspan="2">
                    Piso de Boca
                </td>
                <td>
                    <select class="selectPequenio span1" id="selPisoBoca" >
                        <option value="-1">----</option>
                        <option value="1">Normal</option>
                        <option value="2">Anormal</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    Carrillo
                </td>
                <td>
                    <select class="selectPequenio span1" id="selCarrillo" >
                        <option value="-1">----</option>
                        <option value="1">Normal</option>
                        <option value="2">Anormal</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td colspan="6">
                    <hr>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    Glándulas Salivares
                </td>
                <td>
                    <select class="selectPequenio span1" id="selGlanSalivares" >
                        <option value="-1">----</option>
                        <option value="1">Normal</option>
                        <option value="2">Anormal</option>
                    </select>
                </td>

                <td colspan="2">
                    Maxilares
                </td>
                <td>
                    <select class="selectPequenio span1" id="selMaxilares" >
                        <option value="-1">----</option>
                        <option value="1">Normal</option>
                        <option value="2">Anormal</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    Senos Maxilares
                </td>
                <td>
                    <select class="selectPequenio span1" id="selSenMaxilares" >
                        <option value="-1">----</option>
                        <option value="1">Normal</option>
                        <option value="2">Anormal</option>
                    </select>
                </td>


                <td colspan="2">
                    Músculos Masticadores
                </td>
                <td>
                    <select class="selectPequenio span1" id="selMusMasticadores" >
                        <option value="-1">----</option>
                        <option value="1">Normal</option>
                        <option value="2">Anormal</option>
                    </select>
                </td>
            </tr>
            <tr><td><br></td></tr>
            <tr>
                <td>
                    <b>Sistema: </b>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    Nervioso
                </td>
                <td>
                    <select class="selectPequenio span1" id="selNervioso" >
                        <option value="-1">----</option>
                        <option value="1">Normal</option>
                        <option value="2">Anormal</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    Vascular
                </td>
                <td>
                    <select class="selectPequenio span1" id="selVascular" >
                        <option value="-1">----</option>
                        <option value="1">Normal</option>
                        <option value="2">Anormal</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    Linfático Regional
                </td>
                <td>
                    <select class="selectPequenio span1" id="selLinfatico" >
                        <option value="-1">----</option>
                        <option value="1">Normal</option>
                        <option value="2">Anormal</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td colspan="6">
                    <hr>
                </td>
            </tr>
            <tr><td><b>Examen Dental</b></td></tr>
            
           <tr>
                <td colspan="2">
                    Supernumerarios
                </td>
                <td>
                    <select class="selectPequenio span1" id="selNumerarios" >
                        <option value="-1">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                    </select>
                </td>
            
                <td colspan="2">
                   Abrasión 
                </td>
                <td>
                    <select class="selectPequenio span1" id="selAbrasion" >
                        <option value="-1">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    Manchas
                </td>
                <td>
                    <select class="selectPequenio span1" id="selManchas" >
                        <option value="-1">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                    </select>
                </td>
       
                <td colspan="2">
                    Patología Pulpar
                </td>
                <td>
                    <select class="selectPequenio span1" id="selPatologiaPulpar" >
                        <option value="-1">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    Placa Blanda
                </td>
                <td>
                    <select class="selectPequenio span1" id="selPlacaBlanda" >
                        <option value="-1">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                    </select>
                </td>
           
                <td colspan="2">
                    Placa Calsificada
                </td>
                <td>
                    <select class="selectPequenio span1" id="selPlaCalsificada" >
                        <option value="-1">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    Oclusión
                </td>
                <td>
                    <select class="selectPequenio span1" id="selOclusion" >
                        <option value="-1">----</option>
                        <option value="1">Si</option>
                        <option value="2">No</option>
                    </select>
                </td>
            </tr>
            <tr><td><br></td></tr>
            <tr>
                <td>
                    Otros (Cúal?)
                </td>
            </tr>
            <tr>
                    <td colspan="3">
                        <textarea class="descripcion form-control" id="areaOtrosFisico"></textarea>
                </td>
                
            </tr>
            <tr><td><br></td></tr>
            <tr>
                <td>
                    Observaciones
                </td>
            </tr>
            <tr>
                    <td colspan="3">
                    <textarea class="descripcion form-control" id="areaObsFisico"></textarea>
                </td>
                
            </tr>
            <tr>
                <td colspan="6">
                    <hr>
                </td>
            </tr>

            <tr>
                <td colspan="6" align="center">
                    <table class="centrar">
                        <tbody><tr>

                                <td align="center" colspan="6">
                                    <input type="button" class="btn-primary btn-large" value="Guardar"> 
                                </td>

                            </tr>
                        <br>
                        </tbody>
                    </table>
                </td>
            </tr>
            <tr>
                <td>
                    <br>    
                </td>
            </tr>
        </table>
    </form>
</div>