<script src="<?php echo $this->baseUrl; ?>/js/jquery-1.6.3.min.js" type="text/javascript"></script>


<script>
    $(document).ready(function() {
        $("#content div").hide();
        $("#tabs li:first").attr("id", "current");
        $("#content div:first").fadeIn();

        $('#tabs a').click(function(e) {
            e.preventDefault();
            $("#content div").hide();
            $("#tabs li").attr("id", "");
            $(this).parent().attr("id", "current");
            $('#' + $(this).attr('title')).fadeIn();
        });
    })();
</script>


<ul id="tabs">
    <li><a href="#" title="tab1">Inscribir</a></li>
    <li><a href="#" title="tab2">Consultar</a></li>

</ul>

<div id="content">
    <div id="tab1" class="fancyNormal" style="overflow: hidden">
        <form id="frmCrear" class="tbBorde" style="text-align: left;">
            <table class="centrar" >
                <tr>
                    <td colspan="6" align="center">
                        <H4 class="panel panel-primary btn-primary">ASISTENCIA A TALLERES, JORNADAS Y/O CONFERENCIAS</H4>
                        <br>
                        <br>
                    </td>
                </tr>
                <br>
                <tr>
                    <td>
                        Fecha
                    </td>
                    <td>
                        <input id="txtFechaCita" size="16" type="text" placeholder="Dia/Mes/Año" 
                               data-validation-engine="validate[required,custom[date]]"
                               class="span2 form-control">
                    </td>
                </tr>

                <tr>
                    <td>
                        Nombres del taller y/o conferencia
                    </td>
                    <td colspan="2">
                        <input type="text" class="form-control" id="txtNombreTaller"
                               data-validation-engine="validate[required,onlyLetterSp]"
                               placeholder="Ingrese Nombre del taller">
                    </td>
                </tr>
                <tr>
                    <td>
                        Proyecto Curricular
                    </td>
                    <td>
                        <select class="col-md-4 form-control"
                                id="selProyectoCurricular" 
                                style="overflow: scroll;" 
                                data-validation-engine="validate[required]"
                                data-errormessage="Elija una opcion">
                            <option value="">-----------------------</option>
                            <option value="1">Ingenieria de sistemas</option>
                            <option value="2">Ingenieria en electronica</option>
                        </select>     
                    </td>
                </tr>

                <tr>
                    <td colspan="4">
                        <hr>
                    </td>
                </tr>
                <tr>
                    <td>
                        Nombre de paciente
                    </td>
                    <td>
                        <input type="text" id="txtNombrePaciente" maxlength="11" 
                               placeholder="Nombre Paciente" 
                               data-validation-engine="validate[required,onlyLetterSp]"
                               class="text-input form-control"/>
                    </td>

                </tr>
                <tr>
                    <td>
                        Tipo de documento
                    </td>
                    <td>
                        <select class="col-md-4 form-control"
                                id="selTipoDocumento" 
                                style="overflow: scroll;" 
                                data-validation-engine="validate[required]"
                                data-errormessage="Elija una opcion">
                            <option value="">-----------------------</option>
                            <option value="1">Tarjeta de identidad</option>
                            <option value="2">Cedula de ciudadania</option>
                            <option value="2">Cedula Extranjera</option>
                        </select>     
                    </td>
                </tr>
                <tr>
                    <td>
                        Documento Identidad
                    </td>
                    <td>
                        <input type="text" class="form-control" id="txtDocumentoIdentidad"
                               data-validation-engine="validate[required]"
                               placeholder="Documento">
                    </td>
                </tr>
                <tr>
                    <td colspan="4">
                        <hr>
                    </td>
                </tr>
                <tr>
                    <td>
                        Código
                    </td>
                    <td>
                        <input type="text" class="form-control" id="txtCodigo"
                               data-validation-engine="validate[required,custom[onlyNumberSp,minSize[11]]]"
                               placeholder="CodigoUD"> 

                    </td>
                </tr>
                <tr>
                    <td>
                        Firma
                    </td>
                    <td>
                        <input type="text" class="form-control" id="txtFirma"
                               data-validation-engine="validate[required]"
                               placeholder="Firma valida"> 

                    </td>

                </tr>
                </tbody>
            </table>
            </td>
            </tr>
            <tr>
                <td>
                    <br>    
                </td>
            </tr>
            </table>
        </form>
    </div>

    <!--consultar-->
    <div id="tab2" class="fancyNormal" style="overflow: hidden">

        <form id="frmConsultar" class="tbBorde" style="text-align: left;">
            <table class="centrar" >


                <tr>
                    <td colspan="6" align="center">
                        <H4 class="panel panel-primary btn-primary">CONSULTAR</H4>
                        <br>
                        <br>
                    </td>
                </tr>
                <br>
                <td class="danger"> No </td>
                <td class="danger">NOMBRE</td>
                <td class="danger">IDENTIFICACION</td>
                <td class="danger">CODIGO</td>
                <td class="danger">FIRMA</td>
                
                <tr class="success"></tr>
                <td class="active">-----</td>
                <td class="active">-----</td>
                <td class="active">-----</td>
                <td class="active">-----</td>
                <td class="active">-----</td>
               
                <tr class="active"></tr>
               
                <td class="active">-----</td>
                <td class="active">-----</td>
                <td class="active">-----</td>
                <td class="active">-----</td>
                <td class="active">-----</td>
                <tr class="active"></tr>
                
                <td class="active">-----</td>
                <td class="active">-----</td>
                <td class="active">-----</td>
                <td class="active">-----</td>
                <td class="active">-----</td>
                <tr>
                    
                    <td class="active">-----</td>
                    <td class="active">-----</td>
                    <td class="active">-----</td>
                    <td class="active">-----</td>
                    <td class="active">-----</td>
                </tr>
                <tr>
                    <td>
                        <br>    
                    </td>
                </tr>
            </table>
        </form>
    </div>
</div>
