<!-- barra de menus superior, horizontal -->
        <div >
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand icon-bar" href="#">ODONTO-UD</a>
          </div>
          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li class="active"><a href="<?php echo $this->baseUrl;?>">Inicio</a></li>
              <li class="active"><a href="#about">Pacientes</a></li>
              <li class="active"><a href="#contact">Historias Clinicas</a></li>
              <li class="dropdown active">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Servicios<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Citas</a></li>
                  <li><a href="#">Registro diario de consulta</a></li>
                  <li><a href="#">Seguimiento Realizado</a></li>
                  <li class="divider"></li>
                  <!--class="dropdown-header"-->
                  <li><a href="#">Talleres</a></li>
                  <li><a href="#">Reevaluacion Odontologíca</a></li>
                </ul>
              </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>