<!--barra de menus de la parte vertical-->
<div id="sidebar" role="navigation" class="list-group">
<div class="list-group">
    <a href="#" class="list-group-item active">
        Menu Principal
    </a>
    <a href="<?php echo $this->baseUrl; ?>/citas/asignar" class="list-group-item nav-stacked">Asignar Citas</a>
    <a href="<?php echo $this->baseUrl; ?>/citas/index" class="list-group-item nav-stacked">Consultar Citas</a>
    <a href="<?php echo $this->baseUrl; ?>/citas/cambiar" class="list-group-item nav-stacked">Cambiar Citas</a>
    <a href="<?php echo $this->baseUrl; ?>/citas/eliminar" class="list-group-item nav-stacked">Eliminar Citas</a>
</div>
</div>