      <!--barra de menus izquierdo vertical-->
      <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
          <div class="well sidebar-nav">
            <ul class="nav">
              <li>Sidebar</li>
              <li class="active"><a href="#">Link</a></li>
              <li><a href="./imagenes/banner.png">imagen</a></li>
              <li><a href="#">php</a></li>
              <li>Sidebar</li>
              <li><a href="<?php echo $this->baseUrl; ?>/Estudiante/crear"> Crear</a></li>
                <li><a href="<?php echo $this->baseUrl; ?>/Estudiante/consultar"> Consultar - Actualizar</a></li>
                <li><a href="<?php echo $this->baseUrl; ?>/Estudiante/eliminar"> Eliminar</a></li>
              <li>Sidebar</li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
            </ul>
          </div><!--/.well -->
       </div>
  
      