      <!--barra de menus de la parte vertical-->
      <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
          <div class="well sidebar-nav">
            <ul class="nav">
              <!--<li><a href="<?php echo $this->baseUrl; ?>/imagenes/banner.png">imagen</a></li>-->
              <li>Citas Odontólogicas</li>
              <li class="sidebar-nav sidebar-offcanvas nav nav-tabs"><a href="<?php echo $this->baseUrl; ?>/citas/asignar">Asignar Citas</a></li>
              <li><a href="<?php echo $this->baseUrl; ?>/citas/index">Consultar Citas</a></li>
              <li><a href="<?php echo $this->baseUrl; ?>/citas/cambiar">Modificar Citas</a></li>
              <li><a href="<?php echo $this->baseUrl; ?>/citas/eliminar">Cancelar Citas</a></li>
            </ul>
          </div><!--/.well -->
       </div>
  
      