<!-- barra de menus superior, horizontal -->
<div >
    <div class="navbar-header">

        <div class="navbar-brand controls" >ODONTO-UD</div>
    </div>
    <div class="form-control-static"> 
        <div class="navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="<?php echo $this->baseUrl; ?>">Inicio</a></li>
                <li class="active"><a href="#about">Pacientes</a></li>
                <li class="dropdown active">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Urgencias<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="<?php echo $this->baseUrl; ?>/hclinicas-urgencias/historia">Datos Basicos</a></li>
                        <li><a href="<?php echo $this->baseUrl; ?>/hclinicas-urgencias/anemesis">anamnesis</a></li>
                        <li class="divider"></li>
                        <!--class="dropdown-header"-->
<!--                        <li><a href="#">Talleres</a></li>
                        <li><a href="#">Reevaluacion Odontologíca</a></li>-->
                    </ul>
                </li>
                <li class="active"><a href="<?php echo $this->baseUrl; ?>/citas/asignar">Historias Clinicas</a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</div>