<!--barra de menus de la parte vertical-->
<div id="sidebar" role="navigation" class="list-group" style="text-align: center">
<div class="list-group" style="text-align: center">
    <a href="#" class="list-group-item active">
        Menu Principal
    </a>
    <a href="<?php echo $this->baseUrl; ?>/citas/asignar" class="list-group-item nav-stacked">Asignar Citas</a>
    <a href="<?php echo $this->baseUrl; ?>/citas/consultar" class="list-group-item nav-stacked">Consultar Citas</a>
    <a href="<?php echo $this->baseUrl; ?>/citas/cambiar" class="list-group-item nav-stacked">Cambiar Citas</a>
    <a href="<?php echo $this->baseUrl; ?>/citas/cancelar" class="list-group-item nav-stacked">Eliminar Citas</a>
</div>
</div>

<div id="sidebar" role="navigation" class="list-group">
    <div class="list-group" style="text-align: left">
        <a href="#" class="list-group-item active" style="text-align: center">
        Historia Clínica
    </a>
    <a href="<?php echo $this->baseUrl; ?>/historias-clinicas/crear" class="list-group-item nav-stacked">Información General</a>
    <a href="<?php echo $this->baseUrl; ?>/anemesis/anemesis" class="list-group-item nav-stacked">Anémesis</a>
    <a href="<?php echo $this->baseUrl; ?>/examenfisico/examen-fisico" class="list-group-item nav-stacked">Examen físico Estomatológico</a>
    <a href="<?php echo $this->baseUrl; ?>/historia-clinica/tratamientoejecutado" class="list-group-item nav-stacked">Evaluación del Estado Periodontal</a>
    <a href="<?php echo $this->baseUrl; ?>/citas/eliminar" class="list-group-item nav-stacked">Control Placa</a>
    <a href="<?php echo $this->baseUrl; ?>/citas/eliminar" class="list-group-item nav-stacked">Odontográma</a>
    <a href="<?php echo $this->baseUrl; ?>/citas/eliminar" class="list-group-item nav-stacked">Diagnóstico y Pronóstico</a>
    <a href="<?php echo $this->baseUrl; ?>/historia-clinica/tratamientoejecutado" class="list-group-item nav-stacked">Tratamiento Ejecutado</a>
    <a href="<?php echo $this->baseUrl; ?>/citas/eliminar" class="list-group-item nav-stacked">Odontográma Final</a>
</div>
</div>


<div id="sidebar" role="navigation" class="list-group">
    <div class="list-group" style="text-align: left">
        <a href="#" class="list-group-item active" style="text-align: center">
        Historia Clínica
    </a>
    <a href="<?php echo $this->baseUrl; ?>/hclinica-urgencia/historia-urgencias" class="list-group-item nav-stacked">Datos Básicos</a>
    <a href="<?php echo $this->baseUrl; ?>/hclinica-urgencia/anemesis-urgencia" class="list-group-item nav-stacked">Anémesis Historia Clínica Urgencias</a>
</div>
</div>

<div id="sidebar" role="navigation" class="list-group">
    <div class="list-group" style="text-align: left">
        <a href="#" class="list-group-item active" style="text-align: center">
        Registro diario Consulta
    </a>
    <a href="<?php echo $this->baseUrl; ?>/registro-diario/registroconsulta" class="list-group-item nav-stacked">Registro Diario</a>
    
</div>
</div>


<div id="sidebar" role="navigation" class="list-group">
    <div class="list-group" style="text-align: left">
        <a href="#" class="list-group-item active" style="text-align: center">
        Talleres Odontológicos
    </a>
    <a href="<?php echo $this->baseUrl; ?>/talleres/talleres" class="list-group-item nav-stacked">Talleres</a>
    
</div>
</div>