<!--barra de menus de la parte vertical area izquierda-->

<meta http-equiv="content-type" content="text/html; charset=UTF-8">

<style type='text/css'>
    div.subitem a.list-group-item {
        padding-left: 30px;
    }
</style>

<script type="text/javascript">
    $(window).load(function() {
        $('#sidebar > a').on('mouseover', function(e) {
            e.preventDefault();

            if (!$(this).hasClass("active")) {
                var lastActive = $(this).closest("#sidebar").children(".active");
                lastActive.removeClass("active");
                lastActive.next('div').collapse('hide');
                $(this).addClass("active");
                $(this).next('div').collapse('show');

            }

        });
    });
</script>


<div class="panel panel-default">
    <div id="sidebar" role="navigation" class="list-group" style="text-align: center;">

        <a Style="background-color:silver" href="<?php echo $this->baseUrl(); ?>/index" class="list-group-item active">
            Inicio
        </a>


        <a Style="background-color:#64A0F0" href="#" class="list-group-item" style="text-align: center" data-parent="#sidebar">
            Citas Odontólogicas
        </a>
        <div id="citas" class="list-group subitem collapse">
            <a href="<?php echo $this->baseUrl(); ?>/citas/asignar" class="list-group-item">Asignar</a>
            <a href="<?php echo $this->baseUrl(); ?>/citas/consultar" class="list-group-item">Consultar</a>
            <a href="<?php echo $this->baseUrl(); ?>/citas/cancelar" class="list-group-item">Cancelar</a>
            <a href="<?php echo $this->baseUrl(); ?>/citas/cambiar" class="list-group-item">Cambiar</a>
        </div>

        <a Style="background-color:#64A0F0" href="#" class="list-group-item" style="text-align: center ">
            Historias Clinicas
        </a>

        <div id="historiaClinica" class="list-group subitem collapse">
            <a href="<?php echo $this->baseUrl(); ?>/historias-clinicas/crear" class="list-group-item">Crear</a>
            <a href="<?php echo $this->baseUrl(); ?>/historias-clinicas/crear" class="list-group-item">Consultar</a>
            <a href="<?php echo $this->baseUrl(); ?>/historias-clinicas/crear" class="list-group-item">Seguimiento</a>
        </div>

        <a Style="background-color:#64A0F0" href="<?php echo $this->baseUrl(); ?>/Cita/calendario" class="list-group-item" style="text-align: center " data-parent="#sidebar">
            Consulta
        </a>
        <div id="citas" class="list-group subitem collapse">    
            <a  href="<?php echo $this->baseUrl(); ?>/Cita/calendario" class="list-group-item">Ver Calendario</a>
            <a  href="<?php echo $this->baseUrl(); ?>/Cita/asignarcita" class="list-group-item">Asignar Cita</a>
            <a  href="<?php echo $this->baseUrl(); ?>/Cita/calendariodia" class="list-group-item">Ver Citas del Dia</a>
        </div>



        <a Style="background-color:#64A0F0" href="<?php echo $this->baseUrl(); ?>/Consulta/mcyea" class="list-group-item" style="text-align: center">
            Reportes
        </a>



        <div id="reportes" class="list-group subitem collapse"> 
            <a href="#" class="list-group-item">Consultas del Mes</a>
            <a href="#" class="list-group-item">Estadisticas</a>
            <a href="#" class="list-group-item">Generar Reportes</a>
        </div>


    </div>
</div>
