<link href="<?php echo $this->baseUrl; ?>/bootstrap-3/dist/css/datepicker.css" rel="stylesheet" type="text/css"/>

<link href="<?php echo $this->baseUrl; ?>/bootstrap-3/dist/css/bootstrap-timepicker.min.css" rel="stylesheet" type="text/css"/>

<script src="<?php echo $this->baseUrl; ?>/bootstrap-3/dist/js/bootstrap-datepicker.js" type="text/javascript"></script>

<script src="<?php echo $this->baseUrl; ?>/bootstrap-3/dist/js/bootstrap-timepicker.js" type="text/javascript"></script>


<div class="centrar tbBorde">
    <form id="frmCrear" >
        <H2 align="center" class="panel panel-primary btn-primary">Asignar Nueva Cita</H2>
        <table align="center" class="bottom">
            
            <tbody class="centrar">
            <tr>
                <td>
                    Código de Estudiante
                </td>
                <td>
                    <input name="codigo" type="text" id="codigo" maxlength="11" 
                       placeholder="Código Estudiante" 
                       data-validation-engine="validate[required,custom[onlyNumberSp,/*minSize[11]*/]]"
                       class="text-input form-control"/>
                </td>
                <td></td>
                <td>
                    <input type="button" value="Existe?" id="btnConsultarEstudiante" class="btn btn-primary">
                </td>
            </tr>
            
            <tr>
            <td>
                
            </td>
                <td>
                    <span class="help-inline" id="msjCodigo"></span>
                </td>
            </tr>
            <tr>
                <td>
                    Proyecto Curricular
                </td>
                <td>
            <select class="col-md-4 form-control" name="proyectoCurricular"
                    id="proyectoCurricular" style="overflow: scroll;">
                <option value="1">Ingenieria de sistemas</option>
                <option value="1">Ingenieria de sistemas</option>
            </select>        
                </td>
            </tr>
            <tr>
                <td>
                    Numero de Teléfono
                </td>
                <td>
                    <input name="Telefono" type="text" id="numero" maxlength="7" 
                            placeholder="Número de telefono" 
                            data-validation-engine="validate[required,custom[onlyNumberSp,/*minSize[11]*/]]"
                            class="text-input form-control" />
                </td>
            </tr>
            <tr>
                <td>
                    Nombre de Estudiante
                </td>
                <td>
                    <input name="codigo" type="text" id="codigo" maxlength="11" 
                            placeholder="Nombre Paciente" 
                            data-validation-engine="validate[required]"
                            class="text-input form-control"/>
                </td>
            </tr>
            <tr>
                <td>
                    Hora de la Cita
                </td>
                <td>
                    <input id="hora" type="text" class="form-control" 
                           placeholder="00:00" value="00:00" 
                           data-validation-engine="validate[required]">
                </td>
            </tr>
            <tr>
                <td>
                    Dia de la Cita 
                </td>
                <td>
                    <input id="dp4" size="16" type="text" placeholder="Dia/Mes/Año" 
                        data-validation-engine="validate[required,custom[date]]"
                        class="span2 form-control">
                </td>
            </tr>
            <tr>
                <td>
                    
                </td>
                <td>
                    <input type="button" value="Guardar" id="btnGuardar" class="btn btn-primary">
                </td>
            </tr>
            <tr>
                <td>
                    
                </td>
                <td>
                    <span class="help-block col-md-4" id="msjconfirmacion"></span>
                </td>
            </tr>
            <tr>
                <td>
                    
                </td>
                <td>
                    <a href="<?php echo $this->baseUrl; ?>/index/"><H2 align="center">Ir al inicio</H2></a>
                </td>
            </tr>
            </tbody>
        </table>
    </form>
</div>