<section>
    <!--fancyBox-->
<!--    <link href='<?php echo $this->baseUrl; ?>/validador/fancyBox/jquery.fancyBox-1.3.4.css' rel='stylesheet' />
    <script src='<?php echo $this->baseUrl; ?>/validador/fancyBox/jquery.fancybox-1.3.4.pack.js'></script>-->
    <!--librerias normales-->
    <link href='<?php echo $this->baseUrl; ?>/calendario/fullcalendar/fullcalendar.css' rel='stylesheet' />
    <link href='<?php echo $this->baseUrl; ?>/calendario/fullcalendar/fullcalendar.print.css' rel='stylesheet' media='print' />
    <script src='<?php echo $this->baseUrl; ?>/calendario/fullcalendar/gcal.js'></script>
    <script src='<?php echo $this->baseUrl; ?>/calendario/lib/jquery-ui.custom.min.js'></script>
    <script src='<?php echo $this->baseUrl; ?>/calendario/fullcalendar/fullcalendar.min.js'></script>
    <script>

        $(document).ready(function() {

            var date = new Date();
            var d = date.getDate();
            var m = date.getMonth();
            var y = date.getFullYear();
            var calendar = $('#calendar').fullCalendar({
                /*dayClick: function(date, allDay, jsEvent, view) {
                 var today = new Date();
                 if (today.getHours() != 0 && today.getMinutes() != 0 &&
                 today.getSeconds() != 0 && today.getMilliseconds() != 0) {
                 today.setHours(0, 0, 0, 0);
                 }
                 if (date < today) {
                 alert("Past Date");
                 }
                 }
                 , */hiddenDays: [0, 6],
                allDay: false,
                firstDay: 1,
                monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
                monthNamesShort: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
                dayNames: ['Domingo', 'Lunes', 'Martes', 'Miercoles',
                    'Jueves', 'Viernes', 'Sábado'],
                dayNamesShort: ['Dom', 'Lun', 'Mar', 'Mie', 'Jue', 'Vie', 'Sab'],
                minTime: 6,
                maxTime: 18,
                timeFormat: {
                    agenda: 'H(:mm)' //h:mm{ - h:mm}'
                },
                buttonText:
                        {
                            prev: ' ◄ ',
                            next: ' ► ',
                            prevYear: ' &lt;&lt; ',
                            nextYear: ' &gt;&gt; ',
                            today: 'hoy',
                            month: 'mes',
                            week: 'semana',
                            day: 'día'
                        },
                header: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'agendaDay,agendaWeek,month'
                },
                defaultView: 'agendaDay',
                selectable: false,
                selectHelper: true,
                events: [
                    {
                        id: 1,
                        title: "20072073050 - Tecnología en electronica - 7564857 - Juan Camilo Rodriguez Soza",
                        start: new Date(y, m, 18, 15, 0),
                        end: new Date(y, m, 18, 16, 0),
                        allDay: false
                    },
                    {
                        id: 2,
                        title: "20091078080 - Ingenieria en Telematica - 4225678 - Marcela Chavarro Lopez Tapiero",
                        start: new Date(y, m, 13, 14, 0),
                        end: new Date(y, m, 13, 15, 0),
                        allDay: false
                    },
                    {
                        id: 3,
                        title: "20072073050 - Tecnología en electronica - 7564857 - Juan Camilo Rodriguez Soza",
                        start: new Date(y, m, 16, 7, 0),
                        end: new Date(y, m, 16, 8, 0),
                        allDay: false
                    },
                    {
                        id: 4,
                        title: "20091078080 - Ingenieria en Telematica - 4225678 - Marcela Chavarro Lopez Tapiero",
                        start: new Date(y, m, 3, 10, 0),
                        end: new Date(y, m, 3, 11, 0),
                        allDay: false
                    },
                ]
            });

        });
    </script>
    <div id='calendar' class="tbBorde"></div>
</section>