<h3>Agendamiento de Citas Medicas</h3>
<section>
    <link href='<?php echo $this->baseUrl; ?>/calendario/fullcalendar/fullcalendar.css' rel='stylesheet' />
    <link href='<?php echo $this->baseUrl; ?>/calendario/fullcalendar/fullcalendar.print.css' rel='stylesheet' media='print' />
<!--    <script src='<?php echo $this->baseUrl; ?>/calendario/lib/jquery.min.js'></script>-->
    <script src='<?php echo $this->baseUrl; ?>/calendario/lib/jquery-ui.custom.min.js'></script>
    <script src='<?php echo $this->baseUrl; ?>/calendario/fullcalendar/fullcalendar.min.js'></script>
    <script>

        $(document).ready(function() {

            var date = new Date();
            var d = date.getDate();
            var m = date.getMonth();
            var y = date.getFullYear();

            var calendar = $('#calendar').fullCalendar({
                header: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'month,agendaWeek,agendaDay'
                },
                selectable: true,
                selectHelper: true,
                select: function(start, end, allDay) {
                    var codigo = prompt('Codigo:');
                    var proyectocurr = prompt('Proyecto Curricular:');
                    var numerotel = prompt('Numero de Teléfono:');
                    var nombre = prompt('Nombre Y Apellido:');
                    
                    if (codigo,proyectocurr,numerotel,nombre) {
                        calendar.fullCalendar('renderEvent',
                                {
                                    title: codigo+" - "+proyectocurr,
                                    start: start,
                                    end: end,
                                    allDay: allDay
                                },
                        true // make the event "stick"
                                );
                    }
                    calendar.fullCalendar('unselect');
                },
                editable: true,
                events: [
                    {
                        title: 'Control permanente',
                        start: new Date(y, m, 1)
                    },
                    {
                        title: 'Juan Lozano',
                        start: new Date(y, m, d - 5),
                        end: new Date(y, m, d - 2)
                    },
                    {
                        id: 999,
                        title: 'Sandra Muñoz',
                        start: new Date(y, m, d - 3, 16, 0),
                        allDay: false
                    },
                    {
                        id: 999,
                        title: 'Erika Tobias',
                        start: new Date(y, m, d + 4, 16, 0),
                        allDay: false
                    },
                    {
                        title: 'Jonathan Lopez',
                        start: new Date(y, m, d, 10, 00),
                        end: new Date(y, m, d, 12, 00),
                        allDay: false
                    },
                    {
                        title: 'Edicson Gomez',
                        start: new Date(y, m, d, 12, 0),
                        end: new Date(y, m, d, 14, 0),
                        allDay: false
                    },
                    {
                        title: 'Juan Gomez',
                        start: new Date(y, m, d + 1, 19, 0),
                        end: new Date(y, m, d + 1, 22, 30),
                        allDay: false
                    },
                    {
                        title: 'Camilo Buitrago',
                        start: new Date(y, m, 28),
                        end: new Date(y, m, 29),
                        url: 'http://google.com/'
                    }
                ]
            });

        });

    </script>
    <style>

        body {
            margin-top: 40px;
            text-align: center;
            font-size: 14px;
            font-family: "Lucida Grande",Helvetica,Arial,Verdana,sans-serif;
        }

        #calendar {
            width: 800px;
            float:left;
        }

    </style>

    
    <div id='calendar' class="tbBorde"></div>
</section>
