<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->

    <head>
        <meta charset="utf-8" />
        <title>Crear Estudiante</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport" />
        <meta content="" name="description" />
        <meta content="" name="author" />

        <!-- VALIDAR FORMULARIOS ESTILO----------------------------------------------->
        <link href="<?php echo $this->baseUrl; ?>/archivos/css/validaFormJQ.css" rel="stylesheet" type="text/css" />
        <!---------------------------------------------------------------------------->

    </head>

    <body>

        <div>
            <H1>Crear Nuevo Estudiante</H1>
            <form id="frmCrear">
                <div>
                    <label>Código</label>            
                    <input type="text" name ="codigo" id="codigo" maxlength="11" placeholder="Digite código del Estudiante" class="validate[required,custom[onlyNumberSp,minSize[11]]] text-input" /><!--Caja de texto validada con Vadidator Engine--> 
                    <input type="button" value="Existe?" id="btnConsultarEstudiante">
                    <div>
                        <span class="help-inline" id="msjCodigo"></span>
                    </div>
                </div>
                <div>
                    <label>Nombres</label> 
                    <input type="text" name ="nombres" id="nombres" placeholder="Digite nombres del Estudiante" class="validate[required,custom[onlyLetterSp] text-input" />
                </div>
                <div>
                    <label>Fecha Inscripción</label>            
                    <input type="text" id="fechaIncripcion" placeholder="DD/MM/AAAA" class="validate[required,custom[date]] text-input" /><!----> 
                </div>
                <div>
                    <label>Valor Matricula</label>            
                    <input type="text" id="valorMatricula" placeholder="Digite el valor de la matricula" class="validate[required,custom[onlyNumberSp]] text-input" /><!---->
                </div>
                <div>
                    <label>Personas a Cargo</label>
                    <select class="large m-wrap validate[required]" id="personasCargo" tabindex="1">
                        <option value=""></option>
                        <option value="1">SI</option>
                        <option value="0">NO</option>
                    </select>
                </div>
                <div>
                    <label>Descripción personas a Cargo</label>
                    <div>
                        <textarea  id="descripcion" rows="2" placeholder="En caso afirmativo, con quien vive?" maxlength="100" disabled></textarea>
                    </div>
                </div>
                <div>
                    <label>Asignaturas Perdidas</label>            
                    <input type="text" id="asignaturasPerdidas" placeholder="Asig. perdidas" class="validate[required,custom[integer,min[0]]] text-input" />
                </div>
                <div>
                    <input type="button" value="Guardar" id="btnGuardar">
                </div>
            </form>
            <div>
                 <a href="<?php echo $this->baseUrl; ?>/Index/"><H2>Regresar a Menú</H2></a>
            </div>



        </div>

<!--La etiqueta <script> nos permite insertar codigo javaScript y ajax para el manejo de datos
Podemos implementar nuestras funciones dentro de la etiqueta o llamar un archivo
externo con dichas funciones-->

        <script type='text/javascript'> 
            //Enviamos la URL base a los archivos javaScript.
            var url = '<?php echo $this->baseUrl; ?>'; 
        </script>

        <!--INICIALIZAR LIBRERIA JAVASCRIPT-->
        <script src="<?php echo $this->baseUrl; ?>/archivos/js/jquery-1.8.3.min.js"></script>    

        <!--LIBRERIAS DE VALIDACION DE FORMULARIOS-->
        <script src="<?php echo $this->baseUrl; ?>/archivos/js/jquery.validationEngine.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl; ?>/archivos/js/jquery.validationEngine-es.js" type="text/javascript"></script>
        <!--LIBREIAS DE VALIDACION DE FORMULARIOS-->

        <!--LLAMAMOS AL SCRIPT QUE GESTIONARA LA CREACION DE LOS ESTUDIANTES-->
        <script src="<?php echo $this->baseUrl; ?>/archivos/js/crear.js" type="text/javascript"></script>

        <script>

            $(document).ready(function() {  
                //Inicializamos la libreria validadora para el formulario con id (nombre), "frmCrear"
                $("#frmCrear").validationEngine();
            });
        </script>

        <!--
        El siguiente Script inhabilita o habilita la casilla de 
        descripcion según la opción que se escoja.
        Si este código lo quieren pasar a un archivo individual JavaScript, tienen que hacer
        referencia a el usando la siguiente linea de codigo:
        <script src="<?php echo $this->baseUrl; ?>/archivos/js/nombrearchivo.js" type="text/javascript"></script>
        -->
        <script>   
                    
            //$("#personasCargo") me hace referencia al select de personas a cargo,
            //ya que tiene como id = "personasCargo"
            $("#personasCargo").click(function(){                
                if($("#personasCargo").val()==='0'){
                    $("#descripcion").attr("disabled",'disabled');
                    $("#descripcion").attr("value",'Ninguna');
                }
                else if($("#personasCargo").val()==='1'){
                    $("#descripcion").removeAttr('disabled');
                    $("#descripcion").attr("value",'');
                    $("#descripcion").attr("class",'validate[required]');
                }                
                return false;
            });
        </script>
    </body>


