<div>
    <ul class="nav">
        <li><a href="<?php echo $this->baseUrl?>/Estudiante">Inicio</a></li>
        <li><a>Gestión Estudiantes</a>
            <ul>
                <li><a href="<?php echo $this->baseUrl; ?>/Estudiante/crear"> Crear</a></li>
                <li><a href="<?php echo $this->baseUrl; ?>/Estudiante/consultar"> Consultar - Actualizar</a></li>
                <li><a href="<?php echo $this->baseUrl; ?>/Estudiante/eliminar"> Eliminar</a></li>
            </ul>
        </li>
        <li><a href="">Lo que sea...</a>
            <ul>
                <li><a href="">Servicio 1</a></li>
                <li><a href="">Servicio 2</a></li>
                <li><a href="">Servicio n</a></li>
            </ul>
        </li>
    </ul>
</div> 
