<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <!--<link rel="shortcut icon" href="../../assets/ico/favicon.png">-->

    <!-- Bootstrap core CSS -->
    <!--<link href="./bootstrap-3/dist/css/bootstrap.css" rel="stylesheet"/>
    
    <!-- Bootstrap theme -->
    <link href="./bootstrap-3/dist/css/bootstrap-theme.css" rel="stylesheet"/>
    
    <!--validator theme-->
    <link rel="stylesheet" href="./validador/css/validationEngine.jquery.css" type="text/css"/>
    <link rel="stylesheet" href="./validador/css/template.css" type="text/css"/>
    
    <title>validation plugin</title>
    
    <!-- Custom styles for this template -->
    <!--validator style-->
        <script src="./validador/js/jquery-1.7.2.min.js" type="text/javascript"></script>
    
        <script src="./bootstrap-3/dist/js/bootstrap.js" type="text/javascript" charset="utf-8"></script>
        
        <script src="./validador/js/jquery.validationEngine-es.js" type="text/javascript" charset="utf-8"></script>

        <script src="./validador/js/jquery.validationEngine.js" type="text/javascript" charset="utf-8"></script> 
        
        
        
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="../../assets/js/html5shiv.js"></script>
      <script src="../../assets/js/respond.min.js"></script>
    <![endif]-->
<script>
            jQuery(document).ready(function(){
                // binds form submission and fields to the validation engine
                jQuery("#formID").validationEngine('validate',{promptPosition : "centerRight", scroll: false});
            });
</script> 
        
        
        
        
  </head>

  <body>
     <form id="formID" method="post" action="index.php">
      <br><br><br><br>
      <label  class="label-important">
         Email:
        </label>
        <input type="email" name="email" id="email" required="true"
               data-validation-engine="validate[required,custom[email]]"
               data-errormessage-value-missing="Email is required!" 
               data-errormessage-custom-error="Let me give you a hint: someone@nowhere.com" 
               data-errormessage="This is the fall-back error message."/> 
        <br>
            <input data-validation-engine="validate[required]" type="checkbox" id="agree" name="agree"/>
        <br>
        
        <select name="sport" id="sport" data-validation-engine="validate[required]" id="sport">
            <option value="">Escoja un deporte</option>
            <option value="option1">Tenis</option>
            <option value="option2">Micro futbol</option>
            <option value="option3">Baloncesto</option>
        </select>
        
        
        
        <input type="submit" class="submit" id="validar" value="validar"/>
        
     </form>
  </body>
</html>