<!DOCTYPE html>

<html lang="es">
  <head>
    <meta charset="utf-8"> 
    <!--icono-->
    <link rel="shortcut icon" href="<?php echo $this->baseUrl; ?>./imagenes/favicon.ico">
  </head>
  
  <body>
      <section class="form-content-box">
          
CENTRO DE NEGOCIOS ASISTENCIA TECNOLOGICA INTEGRAL I.E S.A.S ( CENATI SAS )

Nuestra Empresa proporciona servicios en ambientes multiplataforma (Sistemas, Windows, Linus). Somos desarrolladores de software aplicativo destinado a clientes del Sector Financiero, Comercial y a quienes hemos provisto de soluciones de red LAN, suministros de Equipos de cómputo, equipos de comunicación.

CENATI SAS

cuenta con un grupo de profesionales experimentado y altamente calificado en los campos de la informática y  administración de proyectos que garantiza el fortalecimiento de las relaciones de negocios con nuestros clientes y el cumplimiento de las expectativas del mercado.

      </section>
  </body>
</html>