<?php
// module/Album/view/album/album/add.phtml:
$firephp = \FirePHP::getInstance();
$firephp->info($this->locale);
$title = 'Add new album';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('album', array('locale' => $this->locale, 'action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();