<?php
// module/Album/view/album/album/delete.phtml:

$title = 'Delete album';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p><?php echo sprintf($this->translate('Are you sure that you want to delete \'%s\' by \'%s\'?'),
    $this->escapeHtml($album->title),
    $this->escapeHtml($album->artist)
); ?>
</p>
<?php
$url = $this->url('album', array(
    'locale' => $this->locale,
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $album->id; ?>" />
    <input type="submit" name="del" value="<?php echo $this->translate('Yes'); ?>" />
    <input type="submit" name="del" value="<?php echo $this->translate('No'); ?>" />
</div>
</form>