<div id="divNuevoArticulo"  class="fancyNormal" style="overflow: hidden"> 
    <form id="frmCrear" class="tbBorde" style="text-align: left">
        <table class="centrar alinearIzquierda" >


            <tr>
                <td colspan="4" align="center">
                    <H4 class="panel panel-primary btn-primary">REGISTRO DIARIO DE CONSULTA ODONTOLÓGICA</H4>
                    <br>
                    <br>
                </td>
            </tr>
            <br>
            <tr>
                <td>
                    Fecha
                </td>
                <td>
                    <input type="text"  class="form-control " id="txtFechaRegistro">
                </td>
                <td>
                    Hora
                </td>
                <td>
                    <input type="text"  class="form-control " id="txtFechaRegistro">
                </td>
                
            </tr>
            <tr>
                <td>Nombre</td>
                <td>
                    <input type="text"  class="form-control" id="txtNombreRegitro">
                </td>
                <td>
                    Código
                </td>
                <td>
                    <input type="text"  class="form-control" id="txtCodigo">
                </td>
            </tr>
            <tr>
                <td>
                    Sexo
                </td>
                <td>
                    <select class="form-control checkbox-inline" 
                            id="selSexo" 
                            data-validation-engine="validate[required]"
                            data-errormessage="Elija una opcion">
                        <option value="">-- SELECCIONE --</option>
                        <option value="1">M</option>
                        <option value="1">F</option>
                    </select> 
                </td>
            </tr>
            <tr>
                <td>
                    Facultad
                </td>
                <td>
                    <select class="form-control checkbox-inline" 
                            id="selFacultad" 
                            data-validation-engine="validate[required]"
                            data-errormessage="Elija una opcion">
                        <option value="">-- SELECCIONE --</option>
                        <option value="1">Tecnológica</option></select>
                </td>
                <td>
                    Proyecto Curricular
                </td>
                <td>
                    <select class="form-control checkbox-inline"
                            id="selProyectoCurricular"
                            data-validation-engine="validate[required]"
                            data-errormessage="Elija una opcion">
                        <option value="">-- SELECCIONE --</option>
                        <option value="1">Electrónica</option>
                    </select>
                </td>

            </tr>
            <tr>
                <td>
                    <br>
                </td>
            </tr>
            <tr>
                <td colspan="6">
                    <hr>
                </td>
            </tr>
            <tr>
                <td colspan="6" align="center">
                    <table class="centrar">
                        <tbody><tr>

                                <td align="center" colspan="6">
                                    <input type="button" class="btn-primary btn-large" value="Guardar"> 
                                </td>

                            </tr>
                        <br>
                        </tbody>
                    </table>
                </td>
            </tr>
            <tr>
                <td>
                    <br>    
                </td>
            </tr>
        </table>
    </form>
</div>