<script src="<?php echo $this->baseUrl; ?>/archivos/js/beneficiarios.js" type="text/javascript"></script>

<div id="divNuevoArticulo"  class="fancyNormal" style="overflow: hidden"> 
    <form id="frmUrgAnamnesis" class="tbBorde" style="text-align: left">
        <table class="centrar alinearIzquierda">
            <tr>
                <td colspan="6" align="center">
                    <H4 class="panel panel-primary btn-primary">BENEFICIARIO</H4>
                    <br>
                    <br>
                </td>
            </tr>
            <br>


            <tr>
                <td>
                    Tipo vinculación 
                </td>
                <td>
                    <select class="form-control checkbox-inline" 
                            id="selTipoVinculacion"
                            data-validation-engine="validate[required]"
                            data-errormessage="Elija una opcion">
                        <option value="-1">-- SELECCIONE --</option>
                        <option value="estudiante">ESTUDIANTE</option>
                        <option value="docente">DOCENTE</option>
                        <option value="administrativo">ADMINISTRATIVO</option>
                    </select> 
                </td>
                <td>
                    Código
                </td>
                <td>
                    <input type="text" class="form-control" id="txtCodigo" 
                           data-validation-engine="validate[required,onlyLetterSp]"
                           placeholder="Codigo">
                </td>
            </tr>
            <tr>
                <td>
                    Nombres
                </td>
                <td>
                    <input type="text" class="form-control" id="txtNombres" 
                           data-validation-engine="validate[required,onlyLetterSp]"
                           placeholder="Nombres">
                </td>
                <td>
                    Apellidos
                </td>
                <td>
                    <input type="text" class="form-control" id="txtApellidos" 
                           data-validation-engine="validate[required,onlyLetterSp]"
                           placeholder="Apellidos">
                </td>
            </tr>
            <tr>
                <td>
                    Tipo Documento
                </td>
                <td>
                    <select class="form-control checkbox-inline" 
                            id="selTipoDocumento"
                            data-validation-engine="validate[required]"
                            data-errormessage="Elija una opcion">
                        <option value="-1">-- SELECCIONE --</option>
                        <option value="CC">Cedula Ciudadanía</option>
                        <option value="TI">Tarjeta Identidad</option>
                        <option value="CE">Cedula Extrangería</option>
                        <option value="P">Pasaporte</option>
                    </select> 
                </td>
                <td>
                    Documento
                </td>
                <td>
                    <input type="text" class="form-control" id="txtDocumento" 
                           data-validation-engine="validate[required]"
                           placeholder="Documento">
                </td>
            </tr>
            <tr>
                <td>
                    Fecha Nacimiento   
                </td>
                <td>
                    <input type="text" class="span2 form-control" id="txtFechaNacimiento" data-validation-engine="validate[required,custom[date]]" placeholder="Dia/Mes/Año"> 
                </td>
                <td>
                    Tipo Beneficiario
                </td>
                <td>
                    <select class="form-control checkbox-inline" 
                            id="selTipoBeneficiario"
                            data-validation-engine="validate[required]"
                            data-errormessage="Elija una opcion">
                        <option value="-1">-- SELECCIONE --</option>
                        <option value="estudiante">ESTUDIANTE</option>
                        <option value="docente">DOCENTE</option>
                        <option value="administrativo">ADMINISTRATIVO</option>
                        
                    </select>
                </td>
            </tr>
            <tr>
                <td colspan="4">
                    <hr>
                </td>
            </tr>
            <tr>
                <td>
                    Teléfono Fijo
                </td>
                <td>
                    <input type="text" class="form-control" id="txtFijo" 
                           data-validation-engine="validate[required]"
                           placeholder="Teléfono Fijo">
                </td>
                <td>
                    Teléfono Celular
                </td>
                <td>
                    <input type="text" class="form-control" id="txtCelular" 
                           data-validation-engine="validate[required]"
                           placeholder="Teléfono celular">
                </td>
            </tr>
            <tr>
                <td>
                    Email Personal
                </td>
                <td>
                    <input type="text" class="form-control" id="txtEmailPersonal" 
                           data-validation-engine="validate[required]"
                           placeholder="Email Personal">
                </td>
                <td>
                    Email Institucional
                </td>
                <td>
                    <input type="text" class="form-control" id="txtEmailInstitucional" 
                           data-validation-engine="validate[required]"
                           placeholder="Email Institucional">
                </td>
            </tr>
            <tr>
                <td>
                    Tipo Sangre
                </td>
                <td colspan="1">
                   <select class="selectPequenio span1" id="selTipo" data-validation-engine="validate[required]" data-errormessage="Seleccione una opción">
                            <option value="a">A</option>
                            <option value="2">B</option>
                            <option value="3">O</option>
                            <option value="3">AB</option>
                        </select>
                    <select class="selectPequenio span1" id="selRH" data-validation-engine="validate[required]" data-errormessage="Seleccione una opción">
                            <option value="1">+</option>
                            <option value="2">-</option>
                    </select>
                </td>
                <td>
                    Regimén Salud
                </td>
                <td>
                <input type="text" class="form-control" id="txtRegimenSalud" 
                           data-validation-engine="validate[required]"
                           placeholder="Regimen Salud">    
                </td>
            </tr>
           
            <tr>
                <td colspan="4">
                    <hr>
                </td>
            </tr>
            <tr>
                <td>
                    Dirección
                </td>
                <td>
                    <input type="text" class="form-control" id="txtDireccion" 
                           data-validation-engine="validate[required]"
                           placeholder="Dirección">
                </td>
                <td>
                   Barrio 
                </td>
                <td>
                    <input type="text" class="form-control" id="txtBarrio" 
                           data-validation-engine="validate[required]"
                           placeholder="Barrio">
                </td>
            </tr>
            <tr>
                <td>
                    Estrato
                </td>
                <td>
                    <select class="selectPequenio span1" id="selEstrato" data-validation-engine="validate[required]" data-errormessage="Seleccione una opción">
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="1000">Fish</option>
                    </select>
                </td>
                <td>
                    Localidad
                </td>
                <td>
                    <select class="form-control checkbox-inline" id="selLocalidad" data-validation-engine="validate[required]" data-errormessage="Seleccione una opción" style="width: 180px">
                            
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                    País
                </td>
                <td>
                    <select class="form-control checkbox-inline" id="selPais" data-validation-engine="validate[required]" data-errormessage="Seleccione una opción" onchange="llenarSelects(2)" style="width: 180px">
                            
                    </select>
                </td>
                <td>
                    Departamento
                </td>
                <td>
                    <select class="form-control checkbox-inline" id="selDepartamento" data-validation-engine="validate[required]" data-errormessage="Seleccione una opción" onchange="llenarSelects(3);" style="width: 180px">
                     <option value="-1">-- SELECCIONE --</option>       
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                    Municipio
                </td>
                <td>
                   <select class="form-control checkbox-inline" id="selMunicipio" data-validation-engine="validate[required]" data-errormessage="Seleccione una opción" style="width: 180px">
                    <option value="-1">-- SELECCIONE --</option>        
                    </select> 
                </td>
            </tr>
             <tr>
                <td colspan="4">
                    <hr>
                </td>
            </tr>
            <tr>
                <td>
                    <b>Contacto</b>
                </td>
            </tr>
            <tr>
                <td>
                    Nombre
                </td>
                <td>
                    <input type="text" class="form-control" id="txtNombreContacto" 
                           data-validation-engine="validate[required]"
                           placeholder="Nombre Contacto">
                </td>
                <td>
                    Teléfono
                </td>
                <td>
                    <input type="text" class="form-control" id="txtTelfonoContacto" 
                           data-validation-engine="validate[required]"
                           placeholder="Teléfono Contacto">
                </td>
            </tr>
            <tr>
                <td colspan="6" align="center">
                    <table class="centrar">
                        <tbody><tr>

                                <td align="center" colspan="6">
                                    <input type="submit" class="btn-primary btn-large" 
                                           id="btnGuardar" value="Guardar" onclick="guardaBenficiario()"> 
                                </td>

                            </tr>
                        <br>
                        </tbody>
                    </table>
                </td>
            </tr>
            <tr>
                <td>
                    <br>    
                </td>
            </tr>
        </table>
    </form>
</div>