<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
    <HEAD>
        <meta charset="utf-8" />
        <title>Bienestar</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport" />
        <meta content="" name="description" />
        <meta content="" name="author" />

        <!-- VALIDAR FORMULARIOS ESTILO----------------------------------------------->
        <link href="<?php echo $this->baseUrl; ?>/archivos/css/validaFormJQ.css" rel="stylesheet" type="text/css" />
        <!---------------------------------------------------------------------------->

        <!--ESTILO DEL MENU (sidebar) Y PAGINA-->
        <link href="<?php echo $this->baseUrl; ?>/archivos/css/estilos.css" rel="stylesheet" type="text/css" />
        
    </HEAD>

    <BODY>  
        <div id="header">
            <H2>ESTO ES EL HEADER</H2>
        </div>
        <div id="sidebar">
            <?php echo $this->render('sidebar.phtml'); ?> 
        </div>
        <div class="page-content">
            <div id="content">
                <div>
                    <?php echo $this->layout()->content; ?><!--Enviamos los contenidos de todas las vistas-->
                </div>
            </div>
        </div>  
        <div class="footer">
            <H3>UNIVERSIDAD DISTRITAL FRANCISCO JOSE DE CALDAS - BIENESTAR INSTITUCIONAL 2013</H3>
            
            
        </div>


<!--La etiqueta <script> nos permite insertar codigo javaScript y ajax para el manejo de datos
Podemos implementar nuestras funciones dentro de la etiqueta o llamar un archivo
externo con dichas funciones-->

        <script type='text/javascript'> 
            //Enviamos la URL base a los archivos javaScript.
            var url = '<?php echo $this->baseUrl; ?>'; 
        </script>

        <!--INICIALIZAR LIBRERIA JAVASCRIPT-->
        <script src="<?php echo $this->baseUrl; ?>/archivos/js/jquery-1.8.3.min.js"></script>    

        <!--LIBRERIAS DE VALIDACION DE FORMULARIOS-->
        <script src="<?php echo $this->baseUrl; ?>/archivos/js/jquery.validationEngine.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl; ?>/archivos/js/jquery.validationEngine-es.js" type="text/javascript"></script>

        <!--LLAMAMOS AL SCRIPT QUE GESTIONARA LA CREACION DE LOS ESTUDIANTES-->
        <script src="<?php echo $this->baseUrl; ?>/archivos/js/crear.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl; ?>/archivos/js/consultar.js" type="text/javascript"></script>

        <script>

            $(document).ready(function() {  
                //Inicializamos la libreria validadora para el formulario con id (nombre), "frmCrear"
                $("#frmConsultar").validationEngine();
                $("#frmCrear").validationEngine();
            });
        </script>

        <!--
        El siguiente Script inhabilita o habilita la casilla de 
        descripción según la opción que se escoja.
        Si este código lo quieren pasar a un archivo individual JavaScript, tienen que hacer
        referencia a el usando la siguiente linea de codigo:
        <script src="<?php echo $this->baseUrl; ?>/archivos/js/nombrearchivo.js" type="text/javascript"></script>
        -->
        <script>   
                    
            //$("#personasCargo") me hace referencia al select de personas a cargo,
            //ya que tiene como id = "personasCargo"
            $("#personasCargo").click(function(){                
                if($("#personasCargo").val()==='0'){
                    $("#descripcion").attr("disabled",'disabled');
                    $("#descripcion").attr("value",'Ninguna');
                }
                else if($("#personasCargo").val()==='1'){
                    $("#descripcion").removeAttr('disabled');
                    //$("#descripcion").attr("value",'');
                    $("#descripcion").attr("class",'validate[required]');
                }                
                return false;
            });
        </script>

    </BODY>
</HTML>