<?php
$title = $this->translate('Add new song');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($album->title); ?></h1>
<h2><?php echo $this->escapeHtml($title); ?></h2>

<?php
$action = $this->url('song', array(
    'locale' => $this->locale,
    'action' => 'add',
    'album_id' => $album->id
));

$form = $this->form;
$form->setAttribute('action', $action);

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag($form);
