<?php
// module/Album/view/album/song/delete.phtml:

$title = $this->translate('Delete song');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p><?php echo sprintf($this->translate('Are you sure that you want to delete \'%s\' from album \'%s\'?'),
    $this->escapeHtml($song->name),
    $this->escapeHtml($album->title)
); ?>
</p>
<?php
$url = $this->url('song', array(
    'locale' => $this->locale,
    'action' => 'delete',
    'album_id' => $album->id,
    'id'=> $song->id
)); ?>
<form action="<?php echo $url; ?>" method="post">
<div>
  <input type="hidden" name="id" value="<?php echo (int) $album->id; ?>" />
  <input type="submit" name="del" value="<?php echo $this->translate('Yes'); ?>" />
  <input type="submit" name="del" value="<?php echo $this->translate('No'); ?>" />
</div>
</form>