<?php
// module/Album/view/album/album/edit.phtml:

$title = $this->translate('Edit song');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($this->album->title); ?></h1>
<h2><?php echo $this->escapeHtml($title); ?></h2>

<?php
$action = $this->url('song', array(
    'locale' => $this->locale,
    'action' => 'edit',
    'album_id' => $this->album->id,
    'id'     => $this->id,
));

$form = $this->form;
$form->setAttribute('action', $action);
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('album_id'));
echo $this->formRow($form->get('position'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('duration'));
echo $this->formRow($form->get('disc'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();