<!--datepicker-->
<link href="<?php echo $this->baseUrl; ?>/bootstrap-3/dist/css/datepicker.css" rel="stylesheet" type="text/css"/>
<script src="<?php echo $this->baseUrl; ?>/bootstrap-3/js/bootstrap-datepicker.js" type="text/javascript"></script>

<div class="form-content-box form-signin">
    <H1 class=" span2" >Asignar Nueva Cita</H1>
    <form id="frmCrear" >
        <div>
            <label>Código</label>            
            <input name="codigo" type="text" id="codigo" maxlength="11" 
                   placeholder="Digite código del Estudiante" 
                   data-validation-engine="validate[required,custom[onlyNumberSp,/*minSize[11]*/]]"
                   class="text-input form-control" /><!--Caja de texto validada con Vadidator Engine--> 

            <input type="button" value="Existe?" id="btnConsultarEstudiante" class="btn btn-primary">
            <div>
                <span class="help-inline" id="msjCodigo"></span>
            </div>
        </div>
        <div>
            <label>Hora</label> 
            <input type="time" id="hora" placeholder="Hora" 
                   data-validation-engine="validate[required]" 
                   class="text-input form-control" />
        </div>
        <label>fecha datapicker bootstrap</label>

        <div class="label-important" id="dp3" data-date="today();" data-date-format="dd/mm/yyyy">
            <input id="dp4" class="span2" size="16" type="text" placeholder="Dia/Mes/Año" data-validation-engine="validate[required,custom[date]]">
            <span class="add-on"><i class="text-input icon-calendar large"></i></span>
        </div>
        <div>
            <label>Fecha Asignada</label>            
            <input type="text" id="fecha" placeholder="Dia/Mes/Año" 
                   data-validation-engine="validate[required,custom[date]]"
                   class="dateRelease text-input form-control" /><!--validacion de fecha--> 

        </div>
        <div>
            <input type="button" value="Guardar" id="btnGuardar" class="btn btn-primary">
        </div>
        <div>
            <span class="help-block" id="msjconfirmacion"></span>
        </div>
    </form>
    <div>
        <a href="<?php echo $this->baseUrl; ?>/index/"><H2>Regresar a Menú</H2></a>
    </div>
</div>
