
<div>
    <H1>Asignar Nueva Cita</H1>
    <form id="frmCrear">
        <div>
            <label>Código</label>            
            <input name="codigo" type="text" id="codigo" maxlength="11" 
                   placeholder="Digite código del Estudiante" 
                   data-validation-engine="validate[required,custom[onlyNumberSp,/*minSize[11]*/]]"
                   class="text-input" /><!--Caja de texto validada con Vadidator Engine--> 

            <input type="button" value="Existe?" id="btnConsultarEstudiante">
            <div>
                <span class="help-inline" id="msjCodigo"></span>
            </div>
        </div>
        <div>
            <label>Hora</label> 
            <input type="time" id="hora" placeholder="Hora" 
                   data-validation-engine="validate[required]" 
                   class="text-input" />
        </div>
        <label>fecha datapicker bootstrap</label>
        <!--datepicker-->
        <link href="<?php echo $this->baseUrl; ?>/bootstrap-3/dist/css/datepicker.css" rel="stylesheet" type="text/css"/>
        <script src="<?php echo $this->baseUrl; ?>/bootstrap-3/js/bootstrap-datepicker.js" type="text/javascript"></script>
        
        
        <div class="input-append date" id="dp3" data-date="12/02/2013" data-date-format="dd/mm/yyyy">
            <input class="span2" size="16" type="text" value="12/02/2013">
            <span class="add-on"><i class="icon-calendar"></i></span>
        </div>
        <div>
            <label>Fecha Asignada</label>            
            <input type="text" id="fecha" placeholder="Dia/Mes/Año" 
                   data-validation-engine="validate[required,custom[date]]"
                   class="dateRelease" /><!--validacion de fecha--> 

        </div>
        <div>
            <input type="button" value="Guardar" id="btnGuardar">
        </div>
        <div>
            <span class="help-block" id="msjconfirmacion"></span>
        </div>
    </form>
    <div>
        <a href="<?php echo $this->baseUrl; ?>/index/"><H2>Regresar a Menú</H2></a>
    </div>
</div>
