
<div>
    <H1>Asignar Nueva Cita</H1>
    <form id="frmCrear">
        <div>
            <label>Código</label>            
            <input name="codigo" type="text" id="codigo" maxlength="11" 
                   placeholder="Digite código del Estudiante" 
                   data-validation-engine="validate[required,custom[onlyNumberSp,/*minSize[11]*/]]"
                   class="text-input" /><!--Caja de texto validada con Vadidator Engine--> 
            
            <input type="button" value="Existe?" id="btnConsultarEstudiante">
            <div>
                <span class="help-inline" id="msjCodigo"></span>
            </div>
        </div>
        <div>
            <label>Hora</label> 
            <input type="time" id="hora" placeholder="Hora" 
                   data-validation-engine="validate[required]" 
                   class="text-input" />
        </div>
        <div>
            <label>Fecha Asignada</label>            
            <input type="text" id="fecha" placeholder="Dia/Mes/Año" 
                   data-validation-engine="validate[required,custom[date]]"
                   class="text-input" /><!--validacion de fecha--> 
        </div>
        <div>
            <input type="button" value="Guardar" id="btnGuardar">
        </div>
        <div>
            <span class="help-block" id="msjconfirmacion"></span>
        </div>
    </form>
    <div>
        <a href="<?php echo $this->baseUrl; ?>/index/"><H2>Regresar a Menú</H2></a>
    </div>
</div>
