<div class="form-content-box form-signin">
    <table style="text-align: center" class="center table table-striped" width="647" >
        <tr class="active"></tr>
        <td class="danger"> HORA </td>
        <td class="danger">FECHA</td>
        <td class="danger">NOMBRE</td>
        <td class="danger">PROYECTO CURRICULAR</td>
        <td class="danger">IDENTIFICACIÓN</td>
        <td class="danger">TELÉNOFO</td>
        <td class="danger">CAMBIAR</td>
        <tr class="success"></tr>
        <td class="active">-----</td>
        <td class="active">-----</td>
        <td class="active">-----</td>
        <td class="active">-----</td>
        <td class="active">-----</td>
        <td class="active">-----</td>
        <td class="active"><input type="button" id="btnCambiar" class="btn btn-primary" value="Editar"></td>
        <tr class="active"></tr>
        <td class="active">-----</td>
        <td class="active">-----</td>
        <td class="active">-----</td>
        <td class="active">-----</td>
        <td class="active">-----</td>
        <td class="active">-----</td>
        <td class="active"><input type="button" id="btnCambiar" class="btn btn-primary" value="Editar"></td>
        <tr class="active"></tr>
        <td class="active">-----</td>
        <td class="active">-----</td>
        <td class="active">-----</td>
        <td class="active">-----</td>
        <td class="active">-----</td>
        <td class="active">-----</td>
        <td class="active"><input type="button" id="btnCambiar" class="btn btn-primary" value="Editar"></td>
        <tr class="active"></tr>
        <td class="active">-----</td>
        <td class="active">-----</td>
        <td class="active">-----</td>
        <td class="active">-----</td>
        <td class="active">-----</td>
        <td class="active">-----</td>
        <td class="active"><input type="button" id="btnCambiar" class="btn btn-primary" value="Editar"></td>
        <tr class="active"></tr>
        
        <td class="active">-----</td>
        <td class="active">-----</td>
        <td class="active">-----</td>
        <td class="active">-----</td>
        
        <td class="active">-----</td>
        <td class="active">-----</td>
        <td class="active"><input type="button" id="btnCambiar" class="btn btn-primary" value="Editar"></td>
        
    </table>
</div>