<div class="form-content-box form-signin">
    <table style="text-align: center" class="center table table-striped" width="647" >
        <tr class="active"></tr>
        <td class="danger"> HORA </td>
        <td class="danger">FECHA</td>
        <td class="danger">NOMBRE</td>
        <td class="danger">PROYECTO CURRICULAR</td>
        <td class="danger">IDENTIFICACIÓN</td>
        <td class="danger">TELÉNOFO</td>
        <tr class="success"></tr>
        <td class="active">-----</td>
        <td class="active">-----</td>
        <td class="active">-----</td>
        <td class="active">-----</td>
        <td class="active">-----</td>
        <td class="active">-----</td>
        <tr class="active"></tr>
        <td class="active">-----</td>
        <td class="active">-----</td>
        <td class="active">-----</td>
        <td class="active">-----</td>
        <td class="active">-----</td>
        <td class="active">-----</td>
        <tr class="active"></tr>
        <td class="active">-----</td>
        <td class="active">-----</td>
        <td class="active">-----</td>
        <td class="active">-----</td>
        <td class="active">-----</td>
        <td class="active">-----</td>
        <tr>
            <td class="active">-----</td>
            <td class="active">-----</td>
            <td class="active">-----</td>
            <td class="active">-----</td>
            <td class="active">-----</td>
            <td class="active">-----</td>
        </tr>
    </table>
</div>