<div class="container-fluid">
  <div class="row-fluid">
    <div class="span2">
            <!--barra de menus izquierdo vertical-->
      <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
          <div class="well sidebar-nav">
            <ul class="nav">
              <li>Sidebar</li>
              <li class="active"><a href="#">Link</a></li>
              <li><a href="./imagenes/banner.png">imagen</a></li>
              <li><a href="#">php</a></li>
              <li>Sidebar</li>
              <li><a href="<?php echo $this->baseUrl; ?>/Estudiante/crear"> Crear</a></li>
              <li><a href="<?php echo $this->baseUrl; ?>/Estudiante/consultar"> Consultar - Actualizar</a></li>
              <li><a href="<?php echo $this->baseUrl; ?>/Estudiante/eliminar"> Eliminar</a></li>
              <li>Sidebar</li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
            </ul>
          </div><!--/.well -->
       </div>
  

    </div>
    <div class="span10">
      <!--Body content-->
    
<div class="table-responsive">
    <table class="table table-striped" BORDER="1" style="width: 200px; height: 400px"> 
        <tr>
    <td>
      NOMBRE  
    </td>
    <td>
        APELLIDO
    </td>
    <td>
        TELÉFONO
    </td>
</tr>
<tr>
    <td>
        OSCAR
    </td>
    <td>
        GOMEZ
    </td>
    <td>
        131
    </td>
</tr>
<tr>
    <td>
        FISH
    </td>
    <td>
        LÓPEZ
    </td>
    <td>
        90909
    </td>
</tr>
</table>
</div>
      
      </div>
  </div>
</div>